# **Laboratorio plataforma de Streaming** #
Para este Laboratorio de Desafío, vamos a cambiar de ambiente. Ya no estamos en la tienda de tecnología. Ahora eres el Analista de Datos de una plataforma de Streaming (estilo Netflix o Spotify).

In [42]:
import pandas as pd

df_streaming = pd.read_csv('/Users/nando/Ejercicios-Practica-Python/Ciencia de datos/streaming.csv')
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
0,1,Ana_Gomez,Premium,65,3,Norte,15.99
1,2,Carlos_Perez,Basico,12,1,Sur,9.99
2,3,Mariana_Tech,Familiar,85,5,Este,22.99
3,4,Luis_G,Basico,45,2,Norte,9.99
4,5,Ana_Martínez,Premium,30,2,Sur,15.99
5,6,Juan_V,Familiar,110,4,Este,22.99
6,7,Sofia_Corp,Premium,55,4,Oeste,15.99
7,8,Pedro_S,Basico,8,1,Oeste,9.99
8,9,Carlos_Labs,Premium,42,3,Sur,15.99
9,10,Elena_M,Familiar,95,5,Norte,22.99

## **🍿 Desafío 1: Filtro de Clientes VIP (Filtros Combinados)** ##
**Objetivo:** Filtra el DataFrame df_streaming para obtener los registros donde el Tipo_Suscripcion sea exactamente 'Premium' Y las Horas_Reproducidas sean estrictamente mayores a 50.

In [43]:
df_streaming[(df_streaming['Tipo_Suscripcion']== 'Premium') & (df_streaming['Horas_Reproducidas'] > 50 )]

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
0,1,Ana_Gomez,Premium,65,3,Norte,15.99
6,7,Sofia_Corp,Premium,55,4,Oeste,15.99

## **🍿 Desafío 2: Búsqueda de texto parcial (.str.contains)** ##

**Contexto:** El departamento de seguridad detectó que algunas cuentas corporativas o institucionales se registraron con palabras clave en su nombre de usuario.

**Objetivo:** Filtra el DataFrame para encontrar los usuarios cuyo Nombre_Usuario contenga la palabra 'Tech' O la palabra 'Corp'.

In [44]:
df_streaming[(df_streaming['Nombre_Usuario'].str.contains('Tech', na=False))| (df_streaming['Nombre_Usuario'].str.contains('Corp', na=False))]

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
2,3,Mariana_Tech,Familiar,85,5,Este,22.99
6,7,Sofia_Corp,Premium,55,4,Oeste,15.99

## **🍿 Desafío 3: Ordenamiento Jerárquico Complejo** ##

**Contexto:** El equipo de marketing quiere analizar el comportamiento de los usuarios organizados por regiones geográficas. Sin embargo, dentro de cada región, quieren identificar de inmediato a los usuarios que pasan más tiempo consumiendo contenido.

**Objetivo:** Ordena el DataFrame df_streaming por dos columnas al mismo tiempo: primero por Region_Usuario de forma alfabética (ascendente) y, segundo, por Horas_Reproducidas de mayor a menor (descendente).

In [45]:
df_streaming.sort_values(by=['Region_Usuario', 'Horas_Reproducidas'], ascending=[True,False])

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
5,6,Juan_V,Familiar,110,4,Este,22.99
2,3,Mariana_Tech,Familiar,85,5,Este,22.99
9,10,Elena_M,Familiar,95,5,Norte,22.99
0,1,Ana_Gomez,Premium,65,3,Norte,15.99
3,4,Luis_G,Basico,45,2,Norte,9.99
6,7,Sofia_Corp,Premium,55,4,Oeste,15.99
7,8,Pedro_S,Basico,8,1,Oeste,9.99
8,9,Carlos_Labs,Premium,42,3,Sur,15.99
4,5,Ana_Martínez,Premium,30,2,Sur,15.99
1,2,Carlos_Perez,Basico,12,1,Sur,9.99

## **🍿 Desafío 4: Ordenamiento Jerárquico Complejo** ##

**Contexto:** El equipo de retención de clientes quiere lanzar una campaña para reactivar a los usuarios que casi no entran a la plataforma. Necesitan identificar específicamente a las 4 cuentas con menor consumo.

**Objetivo:** Ordena el DataFrame según las Horas_Reproducidas de menor a mayor (ascendente) y quédate únicamente con los 4 primeros registros del resultado.

In [46]:
df_streaming.sort_values(by=['Horas_Reproducidas'], ascending=True).head(4)

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
7,8,Pedro_S,Basico,8,1,Oeste,9.99
1,2,Carlos_Perez,Basico,12,1,Sur,9.99
4,5,Ana_Martínez,Premium,30,2,Sur,15.99
8,9,Carlos_Labs,Premium,42,3,Sur,15.99

## **🍿 Desafío 5: Reporte Ejecutivo Multimétrica** ##

**Contexto:** La dirección financiera necesita un informe rápido sobre los ingresos según el tipo de plan para evaluar la rentabilidad de las suscripciones.

**Objetivo:** Agrupa el DataFrame df_streaming por Tipo_Suscripcion, selecciona la columna Monto_Mensual_USD y obtén en una sola tabla el cobro más bajo ('min'), el cobro más alto ('max') y el total recaudado ('sum').

In [47]:
df_streaming.groupby('Tipo_Suscripcion')['Monto_Mensual_USD'].agg(['min', 'max', 'sum'])

                    min    max    sum
Tipo_Suscripcion
Basico             9.99   9.99  29.97
Familiar          22.99  22.99  68.97
Premium           15.99  15.99  63.96

## **🍿 Desafío 6: Operaciones matemáticas entre columnas** ##

**Contexto:** El departamento de operaciones quiere saber cuánto tiempo pasa un usuario conectado en promedio por cada dispositivo que tiene activo.

**Objetivo:** Crea una nueva columna llamada Horas_Por_Dispositivo que sea el resultado de dividir la columna Horas_Reproducidas entre la columna Dispositivos_Conectados.

In [55]:
df_streaming['Horas_Por_Dispositivo'] = df_streaming['Horas_Reproducidas'] / df_streaming['Dispositivos_Conectados']
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo
0,1,Ana_Gomez,Premium,65,3,Norte,15.99,21.666667
1,2,Carlos_Perez,Basico,12,1,Sur,9.99,12.000000
2,3,Mariana_Tech,Familiar,85,5,Este,22.99,17.000000
3,4,Luis_G,Basico,45,2,Norte,9.99,22.500000
4,5,Ana_Martínez,Premium,30,2,Sur,15.99,15.000000
5,6,Juan_V,Familiar,110,4,Este,22.99,27.500000
6,7,Sofia_Corp,Premium,55,4,Oeste,15.99,13.750000
7,8,Pedro_S,Basico,8,1,Oeste,9.99,8.000000
8,9,Carlos_Labs,Premium,42,3,Sur,15.99,14.000000
9,10,Elena_M,Familiar,95,5,Norte,22.99,19.000000

## **🍿 Desafío 7: Etiquetas condicionales binarias** ##

**Contexto:** El equipo de marketing quiere segmentar a los usuarios según su nivel de consumo para una campaña.

**Objetivo:** Crea una nueva columna llamada Perfil_Consumo. Si el usuario tiene más de 60 Horas_Reproducidas, la columna debe registrar el texto 'Intenso'; de lo contrario, debe registrar 'Moderado'.

In [63]:
#importar numpy
import numpy as np

#Estructura: df_streaming['Nueva_Columna'] = np.where(df['Columna']condicion_logica, 'Valor_Si_Cumple', 'Valor_Si_No_Cumple')
df_streaming['Perfil_Consumo'] = np.where(df_streaming['Horas_Reproducidas'] > 60, 'Intenso','Moderado')
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo
0,1,Ana_Gomez,Premium,65,3,Norte,15.99,21.666667,Intenso
1,2,Carlos_Perez,Basico,12,1,Sur,9.99,12.000000,Moderado
2,3,Mariana_Tech,Familiar,85,5,Este,22.99,17.000000,Intenso
3,4,Luis_G,Basico,45,2,Norte,9.99,22.500000,Moderado
4,5,Ana_Martínez,Premium,30,2,Sur,15.99,15.000000,Moderado
5,6,Juan_V,Familiar,110,4,Este,22.99,27.500000,Intenso
6,7,Sofia_Corp,Premium,55,4,Oeste,15.99,13.750000,Moderado
7,8,Pedro_S,Basico,8,1,Oeste,9.99,8.000000,Moderado
8,9,Carlos_Labs,Premium,42,3,Sur,15.99,14.000000,Moderado
9,10,Elena_M,Familiar,95,5,Norte,22.99,19.000000,Intenso

## **🍿 Desafío 8: Transformación y estandarización de texto** ##

**Contexto:** Para evitar errores en las bases de datos de correos masivos, el equipo de sistemas requiere estandarizar el formato de los planes.

**Objetivo:** Modifica la columna existente Tipo_Suscripcion para que todos sus valores queden guardados completamente en letras minúsculas (por ejemplo, transformar 'Premium' en 'premium').

**Pista:** Pandas tiene un accesorio especial para trabajar con textos llamado .str. Para convertir a minúsculas se usa el método .lower(). La estructura para sobrescribir una columna es:df['Columna'] = df['Columna'].str.lower()

In [65]:
df_streaming['Tipo_Suscripcion'] = df_streaming['Tipo_Suscripcion'].str.lower()
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo
0,1,Ana_Gomez,premium,65,3,Norte,15.99,21.666667,Intenso
1,2,Carlos_Perez,basico,12,1,Sur,9.99,12.000000,Moderado
2,3,Mariana_Tech,familiar,85,5,Este,22.99,17.000000,Intenso
3,4,Luis_G,basico,45,2,Norte,9.99,22.500000,Moderado
4,5,Ana_Martínez,premium,30,2,Sur,15.99,15.000000,Moderado
5,6,Juan_V,familiar,110,4,Este,22.99,27.500000,Intenso
6,7,Sofia_Corp,premium,55,4,Oeste,15.99,13.750000,Moderado
7,8,Pedro_S,basico,8,1,Oeste,9.99,8.000000,Moderado
8,9,Carlos_Labs,premium,42,3,Sur,15.99,14.000000,Moderado
9,10,Elena_M,familiar,95,5,Norte,22.99,19.000000,Intenso

## **🍿 Desafío 9: Multiplicación condicional (Cálculo de Comisiones/Impuestos)** ##

**Contexto:** El departamento de finanzas va a aplicar un impuesto digital del 10% (0.10) sobre el costo del plan mensual, pero únicamente a los usuarios de la región 'Norte'. A las demás regiones se les aplicará un 0% (0).

**Objetivo:** Crea una nueva columna llamada Impuesto_Digital que calcule el valor en dinero de ese impuesto (es decir, multiplicar Monto_Mensual_USD * 0.10 si es del Norte, o guardar 0 si es de otra región).

In [66]:
df_streaming['Impuesto_Digital'] = np.where(df_streaming['Region_Usuario']=='Norte', df_streaming['Monto_Mensual_USD']*0.10, 0)
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital
0,1,Ana_Gomez,premium,65,3,Norte,15.99,21.666667,Intenso,1.599
1,2,Carlos_Perez,basico,12,1,Sur,9.99,12.000000,Moderado,0.000
2,3,Mariana_Tech,familiar,85,5,Este,22.99,17.000000,Intenso,0.000
3,4,Luis_G,basico,45,2,Norte,9.99,22.500000,Moderado,0.999
4,5,Ana_Martínez,premium,30,2,Sur,15.99,15.000000,Moderado,0.000
5,6,Juan_V,familiar,110,4,Este,22.99,27.500000,Intenso,0.000
6,7,Sofia_Corp,premium,55,4,Oeste,15.99,13.750000,Moderado,0.000
7,8,Pedro_S,basico,8,1,Oeste,9.99,8.000000,Moderado,0.000
8,9,Carlos_Labs,premium,42,3,Sur,15.99,14.000000,Moderado,0.000
9,10,Elena_M,familiar,95,5,Norte,22.99,19.000000,Intenso,2.299

## **🍿 Desafío 10: Múltiples condiciones avanzadas con np.select()** ##

**Contexto:** El equipo de soporte quiere clasificar las cuentas por su nivel de riesgo de saturación según los dispositivos que conectan simultáneamente.

**Objetivo:** Crea una nueva columna llamada Riesgo_Conexion bajo la siguiente lógica de tres niveles:    

**Si Dispositivos_Conectados es mayor o igual a 5, la etiqueta debe ser 'Alto'.    
Si Dispositivos_Conectados es igual a 3 o 4, la etiqueta debe ser 'Medio'.  
Si es menor o igual a 2, la etiqueta debe ser 'Bajo'.**

**Pista:** La lógica de np.select() funciona creando dos listas independientes: una para tus preguntas lógicas (condiciones) y otra para las respuestas (opciones). Ambas listas deben tener el mismo orden.

In [68]:
# 1. Creas la lista con todas tus condiciones lógicas
condiciones = [
    (df_streaming['Dispositivos_Conectados'] >= 5),  # Condición 1 (Alto)
    ((df_streaming['Dispositivos_Conectados'] == 3) | (df_streaming['Dispositivos_Conectados'] == 4)),  # Condición 2 (Medio)
    (df_streaming['Dispositivos_Conectados'] <= 2)   # Condición 3 (Bajo)
]

# 2. Creas la lista con los resultados correspondientes en el mismo orden
opciones = ['Alto', 'Medio', 'Bajo']

# 3. Aplicas np.select asignándolo a la nueva columna
df_streaming['Riesgo_Conexion'] = np.select(condiciones, opciones, default='Desconocido')

#Mostrar nueva columna
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65,3,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12,1,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85,5,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45,2,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30,2,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110,4,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55,4,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8,1,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42,3,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95,5,Norte,22.99,19.000000,Intenso,2.299,Alto