# **Laboratorio de pandas**

In [5]:
import pandas as pd

In [6]:
#Cargar archivo

df_tienda = pd.read_csv('/Users/nando/Ejercicios-Practica-Python/Ciencia de datos/reporte_tienda.csv')
df_tienda

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si
2,103,BetaOmega,Software,10,89.99,Baja,Este,No
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si
5,106,BetaOmega,Hardware,3,600.00,Alta,Este,No
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No
8,109,AlphaLabs,Hardware,8,300.00,Media,Sur,No
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si
11,112,DeltaSystems,Software,7,125.00,Media,Este,No
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No
13,114,AlphaLabs,Hardware,1,850.00,Alta,Sur,No
14,115,GlobalNet,Hardware,6,400.00,Media,Oeste,Si
15,116,DeltaSystems,Hardware,4,520.00,Alta,Este,Si
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No
19,120,GlobalNet,Hardware,11,350.00,Alta,Oeste,No

#### **🟢 Ejercicio 1: Inspección Inicial**  
**Misión:** Escribe la línea de código para mostrar en tu consola únicamente las primeras 3 filas de tu DataFrame df_tienda.

In [7]:
df_tienda.head(3)

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si
2,103,BetaOmega,Software,10,89.99,Baja,Este,No

#### **🟢 Ejercicio 2: Radiografía de Dimensiones**  
**Misión:** Obtén de forma exacta cuántas filas y columnas componen este DataFrame sin contarlas a mano.

In [8]:
df_tienda.shape

#Esto para imprimir en otro formato
shape = df_tienda.shape
print('Filas: ',shape[0], '\nColumnas: ',shape[1])

Filas:  20
Columnas:  8

#### **🟢 Ejercicio 3: Aislar una Columna**  
**Misión:** Extrae de forma independiente únicamente los datos pertenecientes a la columna de los nombres de los Clientes.

In [9]:
df_tienda['Cliente']

0         TechCorp
1        AlphaLabs
2        BetaOmega
3         TechCorp
4        AlphaLabs
5        BetaOmega
6         TechCorp
7        GlobalNet
8        AlphaLabs
9        GlobalNet
10        TechCorp
11    DeltaSystems
12       BetaOmega
13       AlphaLabs
14       GlobalNet
15    DeltaSystems
16        TechCorp
17       BetaOmega
18       AlphaLabs
19       GlobalNet
Name: Cliente, dtype: str

#### **🟡 Ejercicio 4: El Combo de Columnas**  
**Misión:** Extrae una sub-hoja de cálculo que muestre únicamente las columnas Cliente y Prioridad al mismo tiempo.

In [10]:
df_tienda[['Cliente', 'Prioridad']]

         Cliente Prioridad
0       TechCorp      Alta
1      AlphaLabs     Media
2      BetaOmega      Baja
3       TechCorp      Baja
4      AlphaLabs      Alta
5      BetaOmega      Alta
6       TechCorp      Baja
7      GlobalNet     Media
8      AlphaLabs     Media
9      GlobalNet      Alta
10      TechCorp      Alta
11  DeltaSystems     Media
12     BetaOmega      Baja
13     AlphaLabs      Alta
14     GlobalNet     Media
15  DeltaSystems      Alta
16      TechCorp     Media
17     BetaOmega      Baja
18     AlphaLabs      Alta
19     GlobalNet      Alta

#### **🟡 Ejercicio 5: Auditoría de Volúmenes**  
**Misión:** Calcula cuántas unidades totales de productos ha vendido la tienda, sumando de forma vertical toda la columna respectiva (Unidades).

In [11]:
unidades_vendidas = df_tienda['Unidades'].sum()
print(f'Unidades vendidas {unidades_vendidas}')

Unidades vendidas 129

#### **🟡 Ejercicio 6: El Contador Logístico**  
**Misión:** Averigua cuántos pedidos se han realizado en total para cada nivel de **Prioridad** (es decir, cuántos son "Alta", cuántos "Media" y cuántos "Baja").

In [26]:
conteo = df_tienda['Prioridad'].value_counts()
print(f'Detalle {conteo}')

Detalle Prioridad
Alta     9
Media    6
Baja     5
Name: count, dtype: int64

#### **🟡 Ejercicio 7: Creación de la columna "Pago_Total"**  
**Misión:** Crea una nueva columna en tu DataFrame llamada **Pago_Total** que calcule de forma automática el costo total de cada pedido. Este valor se obtiene multiplicando la columna Unidades por la columna Precio_Unitario.

In [27]:
df_tienda['Pago_Total'] = df_tienda['Unidades'] * df_tienda['Precio_Unitario']
df_tienda

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No,6002.50
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si,900.00
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
5,106,BetaOmega,Hardware,3,600.00,Alta,Este,No,1800.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
8,109,AlphaLabs,Hardware,8,300.00,Media,Sur,No,2400.00
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si,2200.00
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
13,114,AlphaLabs,Hardware,1,850.00,Alta,Sur,No,850.00
14,115,GlobalNet,Hardware,6,400.00,Media,Oeste,Si,2400.00
15,116,DeltaSystems,Hardware,4,520.00,Alta,Este,Si,2080.00
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00
19,120,GlobalNet,Hardware,11,350.00,Alta,Oeste,No,3850.00

#### **🟡 Ejercicio 8: El Podio de Ventas**  
**Misión:** Ordena todo tu DataFrame de forma descendente (es decir, desde el pedido que pagó más dinero hasta el que pagó menos), basándote en la columna Pago_Total que acabas de crear.

In [28]:
df_tienda_ordenada_Pago = df_tienda.sort_values('Pago_Total', ascending=False)
df_tienda_ordenada_Pago

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No,6002.50
19,120,GlobalNet,Hardware,11,350.00,Alta,Oeste,No,3850.00
14,115,GlobalNet,Hardware,6,400.00,Media,Oeste,Si,2400.00
8,109,AlphaLabs,Hardware,8,300.00,Media,Sur,No,2400.00
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si,2200.00
15,116,DeltaSystems,Hardware,4,520.00,Alta,Este,Si,2080.00
5,106,BetaOmega,Hardware,3,600.00,Alta,Este,No,1800.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si,900.00
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
13,114,AlphaLabs,Hardware,1,850.00,Alta,Sur,No,850.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00

#### **🟡 Ejercicio 9: Filtrado final**  
**Misión:** Necesitamos realizar una auditoría en el inventario. **Filtra el DataFrame df_tienda para obtener únicamente los productos que pertenezcan exactamente a la categoría 'Hardware' Y que tengan un precio unitario igual a 400.**

In [29]:
df_tienda[(df_tienda['Categoria'] == 'Hardware') & (df_tienda['Precio_Unitario'] == 400)]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
14,115,GlobalNet,Hardware,6,400.0,Media,Oeste,Si,2400.0

#### **🟡 Ejercicio 10: El último del bloque**  
**Misión:** La tienda va a lanzar una promoción especial, pero quiere excluir los productos costosos. **Filtra el DataFrame para mostrar los productos que NO pertenecen a la categoría 'Hardware' O cuyo Precio_Unitario sea menor o igual a 150**

In [30]:
df_tienda[(df_tienda['Categoria'] != 'Hardware') | (df_tienda['Precio_Unitario'] <= 150)]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00

#### **🟡 Ejercicio 11: Filtrado múltiple eficiente con .isin()**  
**Contexto**: El departamento de soporte técnico y el área de software necesitan extraer sus datos. Quieres evitar escribir una cadena larga de operadores | (OR).  

**Objetivo:** Filtra el DataFrame para obtener únicamente las filas donde la Categoria sea 'Software' O 'Soporte'.

**Pista:** df_tienda[df_tienda['Categoria'].isin(['Valor1', 'Valor2'])].

In [31]:
df_tienda[df_tienda['Categoria'].isin(['Software', 'Soporte'])]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00

# Filtros y búsquedas #

#### **🟡 Ejercicio 12: Búsqueda de texto parcial con .str.contains()**  
**Objetivo:** Filtra el DataFrame para obtener solo las filas donde el Cliente contenga la palabra 'Corp' (como TechCorp).

**Pista:** Pista: Usa .str.contains('Corp', na=False).

In [32]:
df_tienda[df_tienda['Cliente'].str.contains('Corp', na=False)]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No,6002.50
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si,2200.00
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00

#### **🟡 Ejercicio 13: Filtrado que empieza por... con .str.startswith()**   

**Objetivo:** Filtra el DataFrame para traer las filas donde la Region comience con la letra 'O' (en tus datos esto te devolverá los registros de la región 'Oeste').

**Pista:** La estructura es idéntica al ejercicio anterior, pero cambiando el método por .str.startswith('...').

In [19]:
df_tienda[df_tienda['Region'].str.startswith('Oe')]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
7,108,GlobalNet,Soporte,2,150.0,Media,Oeste,No,300.0
9,110,GlobalNet,Software,20,45.5,Alta,Oeste,Si,910.0
14,115,GlobalNet,Hardware,6,400.0,Media,Oeste,Si,2400.0
19,120,GlobalNet,Hardware,11,350.0,Alta,Oeste,No,3850.0

#### **🟡 Ejercicio 14: Combinando texto y condiciones numéricas**   

**Objetivo:** Encuentra los registros donde el Cliente contenga la palabra 'Labs' (como AlphaLabs) Y que además el Pago_Total sea estrictamente mayor a 1000.

**Pista:** Usa el operador & para unir la condición de texto (.str.contains('Labs', na=False)) y la condición matemática (> 1000). Recuerda envolver cada bloque en sus propios paréntesis ().

In [33]:
df_tienda[(df_tienda['Cliente'].str.contains('Labs', na=False)) & (df_tienda['Pago_Total'] > 1000)]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
8,109,AlphaLabs,Hardware,8,300.0,Media,Sur,No,2400.0

#### **🟡 Ejercicio 15: Filtrado avanzado por exclusión con ~ (Virgulilla)**   

**Objetivo:** Trae todos los registros cuya Categoria NO esté en la lista ['Hardware', 'Software'] (para tus datos, esto debería devolver solo las filas de 'Soporte').

**Pista:** Usa la estructura del Ejercicio 11 con .isin(), pero coloca el símbolo ~ (alt + 126 en Windows / option + ñ en Mac) justo antes de la condición de la columna para invertir el filtro (para decir "que NO esté en").

In [34]:
df_tienda[~df_tienda['Categoria'].isin(['Hardware', 'Software'])]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
3,104,TechCorp,Soporte,1,150.0,Baja,Norte,No,150.0
7,108,GlobalNet,Soporte,2,150.0,Media,Oeste,No,300.0
12,113,BetaOmega,Soporte,5,75.0,Baja,Este,No,375.0
16,117,TechCorp,Soporte,12,120.0,Media,Norte,No,1440.0
18,119,AlphaLabs,Soporte,3,180.0,Alta,Sur,No,540.0

#### **🟡 Ejercicio 16: El filtro de Prioridad Máxima**

**Objetivo:** Muestra los pedidos que tengan Prioridad igual a 'Alta' Y que además hayan aplicado descuento (Descuento_Aplicado igual a 'Si').

**Pista:** Usa el operador & para unir ambas condiciones exactas. Recuerda aislar cada una en sus propios paréntesis ().

In [35]:
df_tienda[(df_tienda['Prioridad'] == 'Alta') & (df_tienda['Descuento_Aplicado'] == 'Si')]

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
4,105,AlphaLabs,Software,4,250.0,Alta,Sur,Si,1000.0
9,110,GlobalNet,Software,20,45.5,Alta,Oeste,Si,910.0
10,111,TechCorp,Hardware,2,1100.0,Alta,Norte,Si,2200.0
15,116,DeltaSystems,Hardware,4,520.0,Alta,Este,Si,2080.0

# Bloque de Ordenamiento #

#### **🟡 Ejercicio 17: Ordenamiento básico ascendente**.  
**Contexto:** El equipo de logística quiere revisar los pedidos empezando por los que compraron menor volumen.

**Objetivo:** Ordena todo el DataFrame df_tienda de menor a mayor según la columna Unidades.

**Pista:** Usa df_tienda.sort_values(by='Nombre_Columna'). Por defecto, Pandas ordena de forma ascendente.

In [40]:
df_tienda.sort_values(by='Unidades')

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00
13,114,AlphaLabs,Hardware,1,850.00,Alta,Sur,No,850.00
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si,900.00
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si,2200.00
5,106,BetaOmega,Hardware,3,600.00,Alta,Este,No,1800.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
15,116,DeltaSystems,Hardware,4,520.00,Alta,Este,Si,2080.00
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No,6002.50
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
14,115,GlobalNet,Hardware,6,400.00,Media,Oeste,Si,2400.00
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
8,109,AlphaLabs,Hardware,8,300.00,Media,Sur,No,2400.00
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
19,120,GlobalNet,Hardware,11,350.00,Alta,Oeste,No,3850.00
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00

#### **🟡 Ejercicio 18: Ordenamiento descendente (Los más caros primero)**.  
**Contexto:** Finanzas quiere auditar las transacciones que generaron los mayores ingresos para la tienda.

**Objetivo:** Ordena el DataFrame de mayor a menor (descendente) según la columna Pago_Total.

**Pista:** Usa el argumento ascending=False.

In [39]:
df_tienda.sort_values(by='Pago_Total', ascending=False)

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No,6002.50
19,120,GlobalNet,Hardware,11,350.00,Alta,Oeste,No,3850.00
14,115,GlobalNet,Hardware,6,400.00,Media,Oeste,Si,2400.00
8,109,AlphaLabs,Hardware,8,300.00,Media,Sur,No,2400.00
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si,2200.00
15,116,DeltaSystems,Hardware,4,520.00,Alta,Este,Si,2080.00
5,106,BetaOmega,Hardware,3,600.00,Alta,Este,No,1800.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si,900.00
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
13,114,AlphaLabs,Hardware,1,850.00,Alta,Sur,No,850.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00

#### **🟡 Ejercicio 19: Ordenamiento jerárquico por múltiples columnas**.  
**Contexto:** Para un reporte de operaciones, queremos organizar los datos por regiones. Pero dentro de cada región, queremos ver los pedidos ordenados desde el precio unitario más alto al más bajo.

**Objetivo:** Ordena el DataFrame por dos columnas: primero por Region de forma alfabética (ascendente), y segundo por Precio_Unitario de mayor a menor (descendente).

**Pista:** Pasa una lista a ambos argumentos: by=['Columna1', 'Columna2'] y ascending=[True, False].

In [43]:
df_tienda.sort_values(by=['Region', 'Precio_Unitario'], ascending=[True, False])

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
5,106,BetaOmega,Hardware,3,600.00,Alta,Este,No,1800.00
15,116,DeltaSystems,Hardware,4,520.00,Alta,Este,Si,2080.00
11,112,DeltaSystems,Software,7,125.00,Media,Este,No,875.00
17,118,BetaOmega,Software,8,95.00,Baja,Este,Si,760.00
2,103,BetaOmega,Software,10,89.99,Baja,Este,No,899.90
12,113,BetaOmega,Soporte,5,75.00,Baja,Este,No,375.00
0,101,TechCorp,Hardware,5,1200.50,Alta,Norte,No,6002.50
10,111,TechCorp,Hardware,2,1100.00,Alta,Norte,Si,2200.00
3,104,TechCorp,Soporte,1,150.00,Baja,Norte,No,150.00
16,117,TechCorp,Soporte,12,120.00,Media,Norte,No,1440.00
6,107,TechCorp,Software,15,99.99,Baja,Norte,Si,1499.85
14,115,GlobalNet,Hardware,6,400.00,Media,Oeste,Si,2400.00
19,120,GlobalNet,Hardware,11,350.00,Alta,Oeste,No,3850.00
7,108,GlobalNet,Soporte,2,150.00,Media,Oeste,No,300.00
9,110,GlobalNet,Software,20,45.50,Alta,Oeste,Si,910.00
13,114,AlphaLabs,Hardware,1,850.00,Alta,Sur,No,850.00
1,102,AlphaLabs,Hardware,2,450.00,Media,Sur,Si,900.00
8,109,AlphaLabs,Hardware,8,300.00,Media,Sur,No,2400.00
4,105,AlphaLabs,Software,4,250.00,Alta,Sur,Si,1000.00
18,119,AlphaLabs,Soporte,3,180.00,Alta,Sur,No,540.00

#### **🟡 Ejercicio 20: Combinando Filtro y Ordenamiento (Nivel Medio)**.  
**Contexto:** El equipo de ventas quiere analizar el rendimiento en la región Sur, pero quiere enfocarse primero en los pedidos que compraron más volumen.

**Objetivo:** Filtra el DataFrame para obtener solo las filas de la Region 'Sur' Y, sobre ese resultado, ordénalo de mayor a menor según las Unidades.

**Pista:** Puedes encadenar los métodos: df_tienda[condicion].sort_values(...).

In [47]:
df_tienda[df_tienda['Region'] == 'Sur'].sort_values(by=['Unidades'],ascending=False)

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
8,109,AlphaLabs,Hardware,8,300.0,Media,Sur,No,2400.0
4,105,AlphaLabs,Software,4,250.0,Alta,Sur,Si,1000.0
18,119,AlphaLabs,Soporte,3,180.0,Alta,Sur,No,540.0
1,102,AlphaLabs,Hardware,2,450.0,Media,Sur,Si,900.0
13,114,AlphaLabs,Hardware,1,850.0,Alta,Sur,No,850.0

#### **🟡 Ejercicio 21: Identificando extremos con .head()**.  
**Contexto:** Dirección quiere premiar a los 3 clientes que realizaron los pagos totales más altos de la tienda.

**Objetivo:** Ordena el DataFrame de forma descendente por Pago_Total y quédate únicamente con los 3 primeros registros.

**Pista:** Usa una estructura similar al ejercicio anterior, pero en lugar de filtrar, encadena el método .head(3) al final de tu ordenamiento.

In [50]:
df_tienda.sort_values(by=['Pago_Total'], ascending=False).head(3)

,ID_Pedido,Cliente,Categoria,Unidades,Precio_Unitario,Prioridad,Region,Descuento_Aplicado,Pago_Total
0,101,TechCorp,Hardware,5,1200.5,Alta,Norte,No,6002.5
19,120,GlobalNet,Hardware,11,350.0,Alta,Oeste,No,3850.0
14,115,GlobalNet,Hardware,6,400.0,Media,Oeste,Si,2400.0