In [1]:
import pandas as pd

df_data = pd.read_csv('/Users/nando/Ejercicios-Practica-Python/Ciencia de datos/Money Control/MoneyControl_14.10.2026.csv', sep=";" , on_bad_lines='skip')
df_data.head(10)

,Fecha,Tipo,Monto,Moneda,Categoría,Persona,Cuenta,Contracuenta,Grupo,Nota
0,19/01/26,Ingresos,"76.026,00",COP,Registro inicial ingreso,NaN,Bolsillo Moto,NaN,NaN,Registro inicial
1,19/01/26,Ingresos,"29.500,00",COP,Registro inicial ingreso,NaN,Bolsillo Fondo Tranquilidad,NaN,NaN,Registro inicial
2,19/01/26,Ingresos,"200.000,00",COP,Registro inicial ingreso,NaN,Bolsillo Nando/Cris,NaN,NaN,Registro inicial
3,19/01/26,Ingresos,"254.000,00",COP,Registro inicial ingreso,NaN,Efectivo,NaN,NaN,Registro inicial
4,19/01/26,Gastos,"- 10.790.850,00",COP,Registro inicial egreso,NaN,TC Visa Davivienda,NaN,NaN,Registro inicial
5,19/01/26,Gastos,"- 3.303.978,00",COP,Registro inicial egreso,NaN,Deuda Servicios,NaN,NaN,Registro inicial
6,19/01/26,Gastos,"- 63.739.352,00",COP,Registro inicial egreso,NaN,Libranza Davivienda,NaN,NaN,NaN
7,19/01/26,Ingresos,"1.803.425,00",COP,Registro inicial ingreso,NaN,Ahorro Fonal,NaN,NaN,Registro inicial
8,19/01/26,Ingresos,"64.358,00",COP,Registro inicial ingreso,NaN,Cuenta Davivienda,NaN,NaN,NaN
9,20/01/26,Gastos,"- 7.840,00",COP,Gastos financieros,NaN,TC Visa Davivienda,NaN,NaN,Comisión avance

# Limpieza de datos #

In [2]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha         1146 non-null   str
 1   Tipo          1146 non-null   str
 2   Monto         1146 non-null   str
 3   Moneda        1146 non-null   str
 4   Categoría     999 non-null    str
 5   Persona       0 non-null      float64
 6   Cuenta        1146 non-null   str
 7   Contracuenta  147 non-null    str
 8   Grupo         0 non-null      float64
 9   Nota          940 non-null    str
dtypes: float64(2), str(8)
memory usage: 168.4 KB

In [3]:
#Contabilizar registros vacíos por columna
df_data.isnull().sum()

Fecha              0
Tipo               0
Monto              0
Moneda             0
Categoría        147
Persona         1146
Cuenta             0
Contracuenta     999
Grupo           1146
Nota             206
dtype: int64

In [4]:
#Eliminar columnas Persona y Grupo porque están vacías 
df_data = df_data.drop(columns=['Persona', 'Grupo'], errors='ignore')
df_data.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,19/01/26,Ingresos,"76.026,00",COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,19/01/26,Ingresos,"29.500,00",COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,19/01/26,Ingresos,"200.000,00",COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,19/01/26,Ingresos,"254.000,00",COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
4,19/01/26,Gastos,"- 10.790.850,00",COP,Registro inicial egreso,TC Visa Davivienda,NaN,Registro inicial

In [5]:
#Convertir Fecha de forma segura (indicando el formato día/mes/año)
df_data['Fecha'] = pd.to_datetime(df_data['Fecha'], format='%d/%m/%y', errors='coerce')
df_data.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,2026-01-19,Ingresos,"76.026,00",COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,2026-01-19,Ingresos,"29.500,00",COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,2026-01-19,Ingresos,"200.000,00",COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,2026-01-19,Ingresos,"254.000,00",COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
4,2026-01-19,Gastos,"- 10.790.850,00",COP,Registro inicial egreso,TC Visa Davivienda,NaN,Registro inicial

In [6]:
#Limpieza del Monto (Especial para formato COP con espacio tras el menos: "- 10.790.850,00")
df_data['Monto'] = df_data['Monto'].astype(str)
df_data['Monto'] = df_data['Monto'].str.replace(' ', '', regex=False)     # Quita espacios (transforma "- " en "-")
df_data['Monto'] = df_data['Monto'].str.replace('.', '', regex=False)     # Quita puntos de miles
df_data['Monto'] = df_data['Monto'].str.replace(',', '.', regex=False)     # Cambia la coma decimal por punto
df_data['Monto'] = pd.to_numeric(df_data['Monto'], errors='coerce')       # Convierte a número flotante

df_data.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,2026-01-19,Ingresos,76026.0,COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,2026-01-19,Ingresos,29500.0,COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,2026-01-19,Ingresos,200000.0,COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,2026-01-19,Ingresos,254000.0,COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
4,2026-01-19,Gastos,-10790850.0,COP,Registro inicial egreso,TC Visa Davivienda,NaN,Registro inicial

In [7]:
#Visualizar registros vacíos para columna categoria y revisar si corresponden todos a Tipo transferencia
df_data[((df_data['Categoría'].isna()) & (df_data['Tipo'] == 'Transferencia'))]

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
10,2026-01-20,Transferencia,26026.0,COP,NaN,Bolsillo Moto,Cuenta Davivienda,NaN
22,2026-01-24,Transferencia,50000.0,COP,NaN,Bolsillo Moto,Efectivo,NaN
23,2026-01-24,Transferencia,25900.0,COP,NaN,Bolsillo Fondo Tranquilidad,Efectivo,NaN
24,2026-01-24,Transferencia,100000.0,COP,NaN,Bolsillo Nando/Cris,Efectivo,NaN
25,2026-01-24,Transferencia,21000.0,COP,NaN,Cuenta Davivienda,Efectivo,NaN
...,...,...,...,...,...,...,...,...
1018,2026-09-29,Transferencia,1600000.0,COP,NaN,Cuenta Davivienda,Bolsillo Pago TC,NaN
1019,2026-09-29,Transferencia,100000.0,COP,NaN,Cuenta Davivienda,Bolsillo Nando/Cris,NaN
1020,2026-09-29,Transferencia,1145.0,COP,NaN,Subsidios Cami,Cuenta Davivienda,NaN
1043,2026-10-09,Transferencia,1800000.0,COP,NaN,Bolsillo Pago TC,Cuenta Davivienda,NaN
1067,2026-10-14,Transferencia,846000.0,COP,NaN,Cuenta Davivienda,Bolsillo Pago TC,NaN

In [11]:
#Imputar registros vacíos de la columna Categoria con Sin Clasificar
df_data['Categoría'] = df_data['Categoría'].fillna('Sin Clasificar')
df_data[df_data['Categoría'] == 'Sin Clasificar']

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
10,2026-01-20,Transferencia,26026.0,COP,Sin Clasificar,Bolsillo Moto,Cuenta Davivienda,NaN
22,2026-01-24,Transferencia,50000.0,COP,Sin Clasificar,Bolsillo Moto,Efectivo,NaN
23,2026-01-24,Transferencia,25900.0,COP,Sin Clasificar,Bolsillo Fondo Tranquilidad,Efectivo,NaN
24,2026-01-24,Transferencia,100000.0,COP,Sin Clasificar,Bolsillo Nando/Cris,Efectivo,NaN
25,2026-01-24,Transferencia,21000.0,COP,Sin Clasificar,Cuenta Davivienda,Efectivo,NaN
...,...,...,...,...,...,...,...,...
1018,2026-09-29,Transferencia,1600000.0,COP,Sin Clasificar,Cuenta Davivienda,Bolsillo Pago TC,NaN
1019,2026-09-29,Transferencia,100000.0,COP,Sin Clasificar,Cuenta Davivienda,Bolsillo Nando/Cris,NaN
1020,2026-09-29,Transferencia,1145.0,COP,Sin Clasificar,Subsidios Cami,Cuenta Davivienda,NaN
1043,2026-10-09,Transferencia,1800000.0,COP,Sin Clasificar,Bolsillo Pago TC,Cuenta Davivienda,NaN
1067,2026-10-14,Transferencia,846000.0,COP,Sin Clasificar,Cuenta Davivienda,Bolsillo Pago TC,NaN

# Análisis financiero #

# 🛠️ Ejercicio 1: El Top de Gastos Reales

### 📌 Contexto Financiero
En tu registro inicial aparecen deudas severas acumuladas en el pasado (como la libranza de más de 63 millones de COP y la tarjeta de crédito de 10 millones de COP). Si dejamos esos saldos dentro del análisis diario, van a distorsionar por completo la realidad, haciéndote creer que gastas millones en un solo día. Para diseñar una estrategia de ahorro efectiva, primero debemos "limpiar el ruido" y aislar tus hábitos de consumo cotidianos actuales. 

### 📝 Enunciado
Filtra el DataFrame original para conservar únicamente las filas donde el `Tipo` sea igual a `"Gastos"`, asegurándote de excluir aquellas transacciones cuya `Categoría` sea `"Registro inicial egreso"`. Con los datos filtrados, realiza una agrupación por `Categoría`, calcula el monto total gastado en cada una de ellas y ordena los resultados de mayor a menor para identificar tus **3 principales salidas de dinero**.

<details>
<summary>Pistas de Pandas</summary>
### 💡 Pistas de Pandas
1. **Para filtrar con múltiples condiciones:** Puedes crear un nuevo DataFrame usando operadores lógicos. Recuerda que para evaluar "igual a" usas `==` y para "diferente de" puedes usar `!=` (o el operador de negación `~`). Ejemplo de estructura: `df[(condicion1) & (condicion2)]`.
2. **Para agrupar y sumar:** Utiliza el método `.groupby('Columna_A')` seguido de `['Columna_B'].sum()`.
3. **Para ordenar:** Al final de la agrupación, encadena el método `.sort_values(ascending=False)` para que los gastos más grandes queden en la cima.
4. **Nota sobre los signos:** Como tus gastos ya vienen con signo negativo desde la base de datos, el ordenamiento de menor a mayor o viceversa dependerá de si prefieres verlos en negativo o aplicar un `.abs()` (valor absoluto) para manejarlos como números positivos.
</details>


### Ajuste de Ruta: Filtro de Gastos Ejecutados ###

Tu tarea en Pandas:
Modifica tu DataFrame de gastos filtrados (el que ya excluye los 'Registro inicial egreso') para que solo conserve las transacciones cuya fecha sea menor o igual al día de hoy.   

• Pistas de Pandas: Puedes importar la librería datetime o usar pd.to_datetime('today') (o la fecha exacta de hoy: 2026-10-14) para hacer la comparación. La estructura sería algo como: df[df['Fecha'] <= '2026-10-14']

In [12]:
#1. Filtrar Tipo Gastos y Categoría diferente a Registro inicial de egreso
#Guardar en nuevo dataframe
df_gastos_filtrados = df_data[(df_data['Tipo'] == 'Gastos') & (df_data['Fecha'] <= '2026-10-31') & ~(df_data['Categoría'] == 'Registro inicial egreso')]
df_gastos_filtrados.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
9,2026-01-20,Gastos,-7840.0,COP,Gastos financieros,TC Visa Davivienda,NaN,Comisión avance
11,2026-01-20,Gastos,-69000.0,COP,Salud,Cuenta Davivienda,NaN,Cita optometria
12,2026-01-20,Gastos,-50000.0,COP,Gadgets y accesorios,Efectivo,NaN,Hideogel 17 Pro Max
13,2026-01-21,Gastos,-65000.0,COP,Gadgets y accesorios,Efectivo,NaN,Case space Protector cámaras
14,2026-01-22,Gastos,-87300.0,COP,Regalos,TC Visa Davivienda,NaN,Cumpleaños Cami

In [13]:
#2. Agrupar y sumar
#3. Ordenar
#4. Aplicar valor absoluto para omitir signo -
df_gastos_filtrados.groupby('Categoría')['Monto'].sum().abs().sort_values(ascending=False)

Categoría
Pago bancos y deudas    57542629.00
Mercado                 15679546.00
Gadgets y accesorios    14785311.00
Salud                    4126300.00
Servicios Públicos       3482190.00
Nando                    2345117.00
Regalos                  2206900.00
Seguros                  2189237.00
Favores                  2183717.00
Servicios Mamá           1926537.06
Moto                     1855282.00
Restaurantes             1591200.00
Entretenimiento          1507300.00
Casa                     1457213.00
Mecato                   1430950.00
Estadio                  1278063.00
Apps/suscripciones       1017077.00
Gastos financieros        924707.93
Deportes                  903670.00
Niño(s)                   676254.00
Transporte/Domicilio      540000.00
Asado                     444584.00
Ajuste egreso             361385.69
Ropa                      361273.00
Celular                   193778.00
Propina/Ofrenda           115000.00
Cris                       83068.00
Restaurante empresa        53000.00
Educación                  15000.00
Name: Monto, dtype: float64

### Excluir categorias que no aplican a los gastos porque son favores

In [14]:
#Excluimos los favores y servicios de mamá que te reembolsan
df_gastos_reales = df_gastos_filtrados[~df_gastos_filtrados['Categoría'].isin(['Favores', 'Servicios Mamá'])]
df_gastos_reales.head(10)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
9,2026-01-20,Gastos,-7840.0,COP,Gastos financieros,TC Visa Davivienda,NaN,Comisión avance
11,2026-01-20,Gastos,-69000.0,COP,Salud,Cuenta Davivienda,NaN,Cita optometria
12,2026-01-20,Gastos,-50000.0,COP,Gadgets y accesorios,Efectivo,NaN,Hideogel 17 Pro Max
13,2026-01-21,Gastos,-65000.0,COP,Gadgets y accesorios,Efectivo,NaN,Case space Protector cámaras
14,2026-01-22,Gastos,-87300.0,COP,Regalos,TC Visa Davivienda,NaN,Cumpleaños Cami
15,2026-01-22,Gastos,-9000.0,COP,Ropa,Efectivo,NaN,Ajuste Boxer y Camiseta
16,2026-01-22,Gastos,-42000.0,COP,Mecato,Efectivo,NaN,NaN
17,2026-01-22,Gastos,-50000.0,COP,Ajuste egreso,Efectivo,NaN,NaN
18,2026-01-23,Gastos,-3050000.0,COP,Gadgets y accesorios,TC Visa Davivienda,NaN,Apple Watch Ultra 3
19,2026-01-24,Gastos,-728932.0,COP,Mercado,TC Visa Davivienda,NaN,NaN

### Aplicamos nuevamente el ordenamiento

In [15]:
#2. Agrupar y sumar
#3. Ordenar
#4. Aplicar valor absoluto para omitir signo -
df_gastos_reales.groupby('Categoría')['Monto'].sum().abs().sort_values(ascending=False)

Categoría
Pago bancos y deudas    57542629.00
Mercado                 15679546.00
Gadgets y accesorios    14785311.00
Salud                    4126300.00
Servicios Públicos       3482190.00
Nando                    2345117.00
Regalos                  2206900.00
Seguros                  2189237.00
Servicios Mamá           1926537.06
Moto                     1855282.00
Restaurantes             1591200.00
Entretenimiento          1507300.00
Casa                     1457213.00
Mecato                   1430950.00
Estadio                  1278063.00
Apps/suscripciones       1017077.00
Gastos financieros        924707.93
Deportes                  903670.00
Niño(s)                   676254.00
Transporte/Domicilio      540000.00
Asado                     444584.00
Ajuste egreso             361385.69
Ropa                      361273.00
Celular                   193778.00
Propina/Ofrenda           115000.00
Cris                       83068.00
Restaurante empresa        53000.00
Educación                  15000.00
Name: Monto, dtype: float64

# 🛠️ Ejercicio 2: El Impacto de lo "Inclasificable"

### 📌 Contexto Financiero
Cuando atravesamos dificultades financieras, cada peso debe tener nombre y apellido. Dejar transacciones en una categoría genérica como "Sin Clasificar" u "Otros" es el equivalente a dejar la puerta de la casa abierta por la noche: no sabes qué se está saliendo por ahí. Si la suma de estos gastos es alta, significa que tienes una fuga invisible de dinero que no estás controlando.

### 📝 Enunciado
Calcula cuánto dinero total se ha ido en la categoría `"Sin Clasificar"` (que asignamos en la limpieza a los valores nulos). Determina también qué porcentaje representa este monto respecto al gasto total real de tu historial (excluyendo los registros iniciales pero manteniendo tus categorías de gasto).

### 💡 Pistas de Pandas
1. **Para calcular el gasto total real:** Puedes usar la suma de la columna `['Monto']` del DataFrame filtrado que creaste en el Ejercicio 1 (`df_gastos_reales`).
2. **Para filtrar la categoría específica:** Selecciona las filas de `df_gastos_reales` donde la columna `Categoría` sea exactamente igual a `'Sin Clasificar'` y aplica `.sum()` a la columna `['Monto']`.
3. **Para el porcentaje:** Divide el total de "Sin Clasificar" entre el gasto total real y multiplícalo por 100.

In [16]:
#1. Calculo el total de los gastos
total_gastos = df_gastos_reales['Monto'].sum()
total_gastos = total_gastos * -1
print(f'El total de gastos es: {total_gastos:2f}')

El total de gastos es: 119092572.680000

In [19]:
#2. Filtrar categoria 'Sin clasificar' y sumar el monto
monto_gastos_sin_clasificar = df_gastos_reales[df_gastos_reales['Categoría'] == 'Sin Clasificar']['Monto'].sum()
print(f'El total de gastos sin clasificar es: {monto_gastos_sin_clasificar}')

El total de gastos sin clasificar es: 0.0

In [20]:
#Calcular el porcentaje de gastos sin clasificar
porcen = monto_gastos_sin_clasificar / total_gastos
print(f'El % de gastos sin clasificar es: {porcen}')

El % de gastos sin clasificar es: 0.0

<details>
<summary>Conclusión del Diagnóstico Financiero</summary>

1. Cero Fugas Invisibles: El resultado de 0.0 COP en gastos Sin Clasificar demuestra que eres sumamente ordenado con tus registros. Sabemos exactamente a dónde va cada peso, lo que significa que el problema no es que el dinero se esfume sin saberlo, sino las decisiones de compra conscientes que estás tomando.
2. El Verdadero Peso de tu Presupuesto: Al limpiar el ruido de los favores y las deudas pesadas, descubrimos que tus dos mayores salidas de dinero reales son Mercado (15.6 millones de COP) y Gadgets y accesorios (14.7 millones de COP).
	• La mirada franca: Gastar casi 15 millones en tecnología y accesorios es un lujo insostenible cuando se arrastran deudas severas. Ese dinero hoy podría estar amortizando tu tarjeta de crédito o tu libranza.

</details>

# 🛠️ Ejercicio 3: Radiografía de los Métodos de Pago

### 📌 Contexto Financiero
A veces el problema no es solo "en qué" gastamos, sino "con qué" pagamos. El uso descontrolado de tarjetas de crédito o cupos de financiamiento crea una ilusión de liquidez que termina alimentando deudas con intereses altísimos (como la tarjeta de Davivienda de 10 millones que vimos al inicio). Necesitamos identificar de cuál de tus cuentas o bolsillos está saliendo la mayor cantidad de dinero real para saber a qué billetera hay que ponerle un freno de mano urgente.

### 📝 Enunciado
Utilizando el `df_gastos_reales`, agrupa las transacciones por la columna `Cuenta`. Calcula la suma total de los montos para cada una y ordena los resultados de mayor a menor gasto para descubrir qué cuenta o tarjeta está canalizando la mayor parte de tus salidas de dinero cotidianas.

<details>
<summary> 💡 ### Pistas de Pandas</summary>
1. **Para agrupar y ordenar:** Aplica una estructura muy similar a la del Ejercicio 1. Usa `.groupby.  ('Columna_Cuenta')`, selecciona la columna `['Monto']`, calcula su `.sum()` y ordénalo con `.sort_values(ascending=True)` para que las cuentas con salidas más grandes (números más negativos) queden arriba.      

2. **Interpretación:** Observa con atención los nombres de las cuentas que aparecen en la cima de la lista.
</details>

In [24]:
df_gastos_reales.groupby('Cuenta')['Monto'].sum().abs().sort_values(ascending=False)

Cuenta
Cuenta Davivienda                  67688554.81
TC Visa Davivienda                 23690808.00
Efectivo                            9084900.00
TC Mastercard Black Bancolombia     5397272.11
ADDI                                4352760.00
Cuenta Bancolombia                  3553778.00
Bolsillo Pago TC                    3371721.00
Bolsillo Fondo Tranquilidad         1373600.00
Bolsillo Nando/Cris                  253327.00
Libre inversión Davi                 138056.45
Subsidios Cami                        69000.00
Bolsillo Personal                     61000.00
Libranza Davivienda                   41408.31
Ahorro Fonal                          16387.00
Name: Monto, dtype: float64

<details>
<summary> 🚨 Conclusiones Crudas y Sinceras: El Diagnóstico del Ejercicio 3  </summary>  
1. **La Falsa Ilusión del Plástico y la Deuda Ágil (\$33.4M COP):** 
   Aunque creas que solo tienes una tarjeta de crédito (Davivienda), tus datos revelan que operás con TRES vehículos de deuda corriente activos: `TC Visa Davivienda`, `TC Mastercard Black Bancolombia` (que puede estar asociada a una cuenta o ser un cupo) y `ADDI`. Sumar más de 33 millones de pesos gastados a través de estos canales es la prueba matemática de que **estás viviendo un estilo de vida que tus ingresos reales no pueden pagar**. Usar ADDI (financiamiento rápido) es el síntoma definitivo de que estás usando deuda para cubrir la falta de liquidez inmediata.

2. **La Hemorragia del Efectivo (\$9.08M COP):**
   Nueve millones de pesos quemados en efectivo es una cifra alarmante para alguien en crisis. El efectivo es el "dinero invisible": se deshace en billetes de \$10.000 y \$20.000 en la calle. Si estás en dificultades financieras, **el efectivo debe ser severamente restringido**, porque es el canal donde la fuerza de voluntad claudica más fácil.

3. **20 Años de Repetición (El "Modo Esclavo" del Banco):**
   Tus salidas están lideradas por `Cuenta Davivienda` (67.6M COP), pero inmediatamente después vienen tus deudas cotidianas. Estás atrapado en un ciclo donde trabajas para pagar la tarjeta, te quedas sin efectivo, vuelves a usar la tarjeta para el mercado o los gadgets, y vuelves a empezar. Si llevas 20 años así, es porque **sigues usando los mismos métodos esperando un resultado diferente**. La tarjeta de crédito y los cupos de financiamiento como ADDI tienen que ser cancelados, congelados o destruidos. No eres una persona apta para usar tarjetas de crédito en este momento de tu vida.

4. **El Freno de Mano Urgente:**
   Para romper un ciclo de 20 años de deudas, la primera regla es: **"Si estás en un hoyo, deja de cavar"**. Cada vez que pasas la tarjeta de Davivienda o pides un crédito en ADDI para comprar algo que no es comida o salud, estás decidiendo voluntariamente prolongar tu crisis un año más.

</details>

# 🛠️ Ejercicio 4: El Índice de Gasto Discrecional (Deseos vs. Necesidades)

### 📌 Contexto Financiero
Cuando se llevan 20 años acumulando deudas, el cerebro se acostumbra a normalizar ciertos gastos, convenciéndonos de que son "necesarios". Para romper el ciclo, debemos clasificar tus gastos con total frialdad en dos grupos: **Supervivencia** (Arriendo, Servicios públicos, Salud, Mercado básico) y **Deseo/Estilo de Vida** (Estadio, Mecato, Gadgets, Entretenimiento, Restaurantes). Si tu gasto en "Deseos" es alto mientras estás en crisis, estás saboteando activamente tu propia libertad financiera.

### 📝 Enunciado
Crea una lista con las categorías que representan "Deseos o Estilo de Vida" (por ejemplo: `Gadgets y accesorios`, `Restaurantes`, `Entretenimiento`, `Mecato`, `Estadio`, `Regalos`, `Apps/suscripciones`). Filtra tu `df_gastos_reales` para calcular cuánto dinero suman estas categorías en total y qué porcentaje representan del total de tus gastos reales.

### 💡 Pistas de Pandas
1. **Para filtrar por una lista de categorías:** Crea una lista de Python con los nombres exactos de las categorías de lujos: `lista_lujos = ['Mecato', 'Estadio', ...]`.
2. **Usa el método `.isin()`:** Filtra tu DataFrame aplicando la condición: `df_gastos_reales[df_gastos_reales['Categoría'].isin(lista_lujos)]`.
3. **Suma y compara:** Calcula la suma de la columna `['Monto']` para esta selección, aplícale `.abs()` y divídela entre el `total_gastos` que hallaste en el Ejercicio 2 para sacar el porcentaje de dinero que se está yendo en "deseos".

In [ ]:
df_gastos_reales[df_gastos_reales['Categoría'].isin(['Gadgets y accesorios', 'Restaurantes', 'Entretenimiento', 'Mecato', 'Estadio', 'Regalos', 'Apps/suscripciones'])]

TypeError: 'method' object is not subscriptable