In [35]:
import pandas as pd

df_data = pd.read_csv('/Users/nando/Ejercicios-Practica-Python/Ciencia de datos/6. Laboratorio Money Control/MoneyControl_14.10.2026.csv', sep=";" , on_bad_lines='skip')
df_data.head(10)

,Fecha,Tipo,Monto,Moneda,Categoría,Persona,Cuenta,Contracuenta,Grupo,Nota
0,19/01/26,Ingresos,"76.026,00",COP,Registro inicial ingreso,NaN,Bolsillo Moto,NaN,NaN,Registro inicial
1,19/01/26,Ingresos,"29.500,00",COP,Registro inicial ingreso,NaN,Bolsillo Fondo Tranquilidad,NaN,NaN,Registro inicial
2,19/01/26,Ingresos,"200.000,00",COP,Registro inicial ingreso,NaN,Bolsillo Nando/Cris,NaN,NaN,Registro inicial
3,19/01/26,Ingresos,"254.000,00",COP,Registro inicial ingreso,NaN,Efectivo,NaN,NaN,Registro inicial
4,19/01/26,Gastos,"- 10.790.850,00",COP,Registro inicial egreso,NaN,TC Visa Davivienda,NaN,NaN,Registro inicial
5,19/01/26,Gastos,"- 3.303.978,00",COP,Registro inicial egreso,NaN,Deuda Servicios,NaN,NaN,Registro inicial
6,19/01/26,Gastos,"- 63.739.352,00",COP,Registro inicial egreso,NaN,Libranza Davivienda,NaN,NaN,NaN
7,19/01/26,Ingresos,"1.803.425,00",COP,Registro inicial ingreso,NaN,Ahorro Fonal,NaN,NaN,Registro inicial
8,19/01/26,Ingresos,"64.358,00",COP,Registro inicial ingreso,NaN,Cuenta Davivienda,NaN,NaN,NaN
9,20/01/26,Gastos,"- 7.840,00",COP,Gastos financieros,NaN,TC Visa Davivienda,NaN,NaN,Comisión avance

# Limpieza de datos #

In [36]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha         1146 non-null   str
 1   Tipo          1146 non-null   str
 2   Monto         1146 non-null   str
 3   Moneda        1146 non-null   str
 4   Categoría     999 non-null    str
 5   Persona       0 non-null      float64
 6   Cuenta        1146 non-null   str
 7   Contracuenta  147 non-null    str
 8   Grupo         0 non-null      float64
 9   Nota          940 non-null    str
dtypes: float64(2), str(8)
memory usage: 168.4 KB

In [37]:
#Contabilizar registros vacíos por columna
df_data.isnull().sum()

Fecha              0
Tipo               0
Monto              0
Moneda             0
Categoría        147
Persona         1146
Cuenta             0
Contracuenta     999
Grupo           1146
Nota             206
dtype: int64

In [38]:
#Eliminar columnas Persona y Grupo porque están vacías 
df_data = df_data.drop(columns=['Persona', 'Grupo'], errors='ignore')
df_data.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,19/01/26,Ingresos,"76.026,00",COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,19/01/26,Ingresos,"29.500,00",COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,19/01/26,Ingresos,"200.000,00",COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,19/01/26,Ingresos,"254.000,00",COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
4,19/01/26,Gastos,"- 10.790.850,00",COP,Registro inicial egreso,TC Visa Davivienda,NaN,Registro inicial

In [39]:
#Convertir Fecha de forma segura (indicando el formato día/mes/año)
df_data['Fecha'] = pd.to_datetime(df_data['Fecha'], format='%d/%m/%y', errors='coerce')
df_data.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,2026-01-19,Ingresos,"76.026,00",COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,2026-01-19,Ingresos,"29.500,00",COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,2026-01-19,Ingresos,"200.000,00",COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,2026-01-19,Ingresos,"254.000,00",COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
4,2026-01-19,Gastos,"- 10.790.850,00",COP,Registro inicial egreso,TC Visa Davivienda,NaN,Registro inicial

In [40]:
#Limpieza del Monto (Especial para formato COP con espacio tras el menos: "- 10.790.850,00")
df_data['Monto'] = df_data['Monto'].astype(str)
df_data['Monto'] = df_data['Monto'].str.replace(' ', '', regex=False)     # Quita espacios (transforma "- " en "-")
df_data['Monto'] = df_data['Monto'].str.replace('.', '', regex=False)     # Quita puntos de miles
df_data['Monto'] = df_data['Monto'].str.replace(',', '.', regex=False)     # Cambia la coma decimal por punto
df_data['Monto'] = pd.to_numeric(df_data['Monto'], errors='coerce')       # Convierte a número flotante

df_data.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,2026-01-19,Ingresos,76026.0,COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,2026-01-19,Ingresos,29500.0,COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,2026-01-19,Ingresos,200000.0,COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,2026-01-19,Ingresos,254000.0,COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
4,2026-01-19,Gastos,-10790850.0,COP,Registro inicial egreso,TC Visa Davivienda,NaN,Registro inicial

In [41]:
#Visualizar registros vacíos para columna categoria y revisar si corresponden todos a Tipo transferencia
df_data[((df_data['Categoría'].isna()) & (df_data['Tipo'] == 'Transferencia'))]

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
10,2026-01-20,Transferencia,26026.0,COP,NaN,Bolsillo Moto,Cuenta Davivienda,NaN
22,2026-01-24,Transferencia,50000.0,COP,NaN,Bolsillo Moto,Efectivo,NaN
23,2026-01-24,Transferencia,25900.0,COP,NaN,Bolsillo Fondo Tranquilidad,Efectivo,NaN
24,2026-01-24,Transferencia,100000.0,COP,NaN,Bolsillo Nando/Cris,Efectivo,NaN
25,2026-01-24,Transferencia,21000.0,COP,NaN,Cuenta Davivienda,Efectivo,NaN
...,...,...,...,...,...,...,...,...
1018,2026-09-29,Transferencia,1600000.0,COP,NaN,Cuenta Davivienda,Bolsillo Pago TC,NaN
1019,2026-09-29,Transferencia,100000.0,COP,NaN,Cuenta Davivienda,Bolsillo Nando/Cris,NaN
1020,2026-09-29,Transferencia,1145.0,COP,NaN,Subsidios Cami,Cuenta Davivienda,NaN
1043,2026-10-09,Transferencia,1800000.0,COP,NaN,Bolsillo Pago TC,Cuenta Davivienda,NaN
1067,2026-10-14,Transferencia,846000.0,COP,NaN,Cuenta Davivienda,Bolsillo Pago TC,NaN

In [42]:
#Imputar registros vacíos de la columna Categoria con Sin Clasificar
df_data['Categoría'] = df_data['Categoría'].fillna('Sin Clasificar')
df_data[df_data['Categoría'] == 'Sin Clasificar']

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
10,2026-01-20,Transferencia,26026.0,COP,Sin Clasificar,Bolsillo Moto,Cuenta Davivienda,NaN
22,2026-01-24,Transferencia,50000.0,COP,Sin Clasificar,Bolsillo Moto,Efectivo,NaN
23,2026-01-24,Transferencia,25900.0,COP,Sin Clasificar,Bolsillo Fondo Tranquilidad,Efectivo,NaN
24,2026-01-24,Transferencia,100000.0,COP,Sin Clasificar,Bolsillo Nando/Cris,Efectivo,NaN
25,2026-01-24,Transferencia,21000.0,COP,Sin Clasificar,Cuenta Davivienda,Efectivo,NaN
...,...,...,...,...,...,...,...,...
1018,2026-09-29,Transferencia,1600000.0,COP,Sin Clasificar,Cuenta Davivienda,Bolsillo Pago TC,NaN
1019,2026-09-29,Transferencia,100000.0,COP,Sin Clasificar,Cuenta Davivienda,Bolsillo Nando/Cris,NaN
1020,2026-09-29,Transferencia,1145.0,COP,Sin Clasificar,Subsidios Cami,Cuenta Davivienda,NaN
1043,2026-10-09,Transferencia,1800000.0,COP,Sin Clasificar,Bolsillo Pago TC,Cuenta Davivienda,NaN
1067,2026-10-14,Transferencia,846000.0,COP,Sin Clasificar,Cuenta Davivienda,Bolsillo Pago TC,NaN

# Análisis financiero #

# 🛠️ Ejercicio 1: El Top de Gastos Reales

### 📌 Contexto Financiero
En tu registro inicial aparecen deudas severas acumuladas en el pasado (como la libranza de más de 63 millones de COP y la tarjeta de crédito de 10 millones de COP). Si dejamos esos saldos dentro del análisis diario, van a distorsionar por completo la realidad, haciéndote creer que gastas millones en un solo día. Para diseñar una estrategia de ahorro efectiva, primero debemos "limpiar el ruido" y aislar tus hábitos de consumo cotidianos actuales. 

### 📝 Enunciado
Filtra el DataFrame original para conservar únicamente las filas donde el `Tipo` sea igual a `"Gastos"`, asegurándote de excluir aquellas transacciones cuya `Categoría` sea `"Registro inicial egreso"`. Con los datos filtrados, realiza una agrupación por `Categoría`, calcula el monto total gastado en cada una de ellas y ordena los resultados de mayor a menor para identificar tus **3 principales salidas de dinero**.


### 💡 Pistas de Pandas

<details>
1. **Para filtrar con múltiples condiciones:** Puedes crear un nuevo DataFrame usando operadores lógicos. Recuerda que para evaluar "igual a" usas `==` y para "diferente de" puedes usar `!=` (o el operador de negación `~`). Ejemplo de estructura: `df[(condicion1) & (condicion2)]`.
2. **Para agrupar y sumar:** Utiliza el método `.groupby('Columna_A')` seguido de `['Columna_B'].sum()`.
3. **Para ordenar:** Al final de la agrupación, encadena el método `.sort_values(ascending=False)` para que los gastos más grandes queden en la cima.
4. **Nota sobre los signos:** Como tus gastos ya vienen con signo negativo desde la base de datos, el ordenamiento de menor a mayor o viceversa dependerá de si prefieres verlos en negativo o aplicar un `.abs()` (valor absoluto) para manejarlos como números positivos.
</details>


### Ajuste de Ruta: Filtro de Gastos Ejecutados ###

Tu tarea en Pandas:
Modifica tu DataFrame de gastos filtrados (el que ya excluye los 'Registro inicial egreso') para que solo conserve las transacciones cuya fecha sea menor o igual al día de hoy.   

• Pistas de Pandas: Puedes importar la librería datetime o usar pd.to_datetime('today') (o la fecha exacta de hoy: 2026-10-14) para hacer la comparación. La estructura sería algo como: df[df['Fecha'] <= '2026-10-14']

In [43]:
#1. Filtrar Tipo Gastos y Categoría diferente a Registro inicial de egreso
#Guardar en nuevo dataframe
df_gastos_filtrados = df_data[(df_data['Tipo'] == 'Gastos') & (df_data['Fecha'] <= '2026-10-31') & ~(df_data['Categoría'] == 'Registro inicial egreso')]
df_gastos_filtrados.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
9,2026-01-20,Gastos,-7840.0,COP,Gastos financieros,TC Visa Davivienda,NaN,Comisión avance
11,2026-01-20,Gastos,-69000.0,COP,Salud,Cuenta Davivienda,NaN,Cita optometria
12,2026-01-20,Gastos,-50000.0,COP,Gadgets y accesorios,Efectivo,NaN,Hideogel 17 Pro Max
13,2026-01-21,Gastos,-65000.0,COP,Gadgets y accesorios,Efectivo,NaN,Case space Protector cámaras
14,2026-01-22,Gastos,-87300.0,COP,Regalos,TC Visa Davivienda,NaN,Cumpleaños Cami

In [44]:
#2. Agrupar y sumar
#3. Ordenar
#4. Aplicar valor absoluto para omitir signo -
df_gastos_filtrados.groupby('Categoría')['Monto'].sum().abs().sort_values(ascending=False)

Categoría
Pago bancos y deudas    57542629.00
Mercado                 15679546.00
Gadgets y accesorios    14785311.00
Salud                    4126300.00
Servicios Públicos       3482190.00
Nando                    2345117.00
Regalos                  2206900.00
Seguros                  2189237.00
Favores                  2183717.00
Servicios Mamá           1926537.06
Moto                     1855282.00
Restaurantes             1591200.00
Entretenimiento          1507300.00
Casa                     1457213.00
Mecato                   1430950.00
Estadio                  1278063.00
Apps/suscripciones       1017077.00
Gastos financieros        924707.93
Deportes                  903670.00
Niño(s)                   676254.00
Transporte/Domicilio      540000.00
Asado                     444584.00
Ajuste egreso             361385.69
Ropa                      361273.00
Celular                   193778.00
Propina/Ofrenda           115000.00
Cris                       83068.00
Restaurante empresa        53000.00
Educación                  15000.00
Name: Monto, dtype: float64

### Excluir categorias que no aplican a los gastos porque son favores

In [45]:
#Excluimos los favores y servicios de mamá que te reembolsan
df_gastos_reales = df_gastos_filtrados[~df_gastos_filtrados['Categoría'].isin(['Favores', 'Servicios Mamá'])]
df_gastos_reales.head(10)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
9,2026-01-20,Gastos,-7840.0,COP,Gastos financieros,TC Visa Davivienda,NaN,Comisión avance
11,2026-01-20,Gastos,-69000.0,COP,Salud,Cuenta Davivienda,NaN,Cita optometria
12,2026-01-20,Gastos,-50000.0,COP,Gadgets y accesorios,Efectivo,NaN,Hideogel 17 Pro Max
13,2026-01-21,Gastos,-65000.0,COP,Gadgets y accesorios,Efectivo,NaN,Case space Protector cámaras
14,2026-01-22,Gastos,-87300.0,COP,Regalos,TC Visa Davivienda,NaN,Cumpleaños Cami
15,2026-01-22,Gastos,-9000.0,COP,Ropa,Efectivo,NaN,Ajuste Boxer y Camiseta
16,2026-01-22,Gastos,-42000.0,COP,Mecato,Efectivo,NaN,NaN
17,2026-01-22,Gastos,-50000.0,COP,Ajuste egreso,Efectivo,NaN,NaN
18,2026-01-23,Gastos,-3050000.0,COP,Gadgets y accesorios,TC Visa Davivienda,NaN,Apple Watch Ultra 3
19,2026-01-24,Gastos,-728932.0,COP,Mercado,TC Visa Davivienda,NaN,NaN

### Aplicamos nuevamente el ordenamiento

In [46]:
#2. Agrupar y sumar
#3. Ordenar
#4. Aplicar valor absoluto para omitir signo -
df_gastos_reales.groupby('Categoría')['Monto'].sum().abs().sort_values(ascending=False)

Categoría
Pago bancos y deudas    57542629.00
Mercado                 15679546.00
Gadgets y accesorios    14785311.00
Salud                    4126300.00
Servicios Públicos       3482190.00
Nando                    2345117.00
Regalos                  2206900.00
Seguros                  2189237.00
Servicios Mamá           1926537.06
Moto                     1855282.00
Restaurantes             1591200.00
Entretenimiento          1507300.00
Casa                     1457213.00
Mecato                   1430950.00
Estadio                  1278063.00
Apps/suscripciones       1017077.00
Gastos financieros        924707.93
Deportes                  903670.00
Niño(s)                   676254.00
Transporte/Domicilio      540000.00
Asado                     444584.00
Ajuste egreso             361385.69
Ropa                      361273.00
Celular                   193778.00
Propina/Ofrenda           115000.00
Cris                       83068.00
Restaurante empresa        53000.00
Educación                  15000.00
Name: Monto, dtype: float64

# 🛠️ Ejercicio 2: El Impacto de lo "Inclasificable"

### 📌 Contexto Financiero
Cuando atravesamos dificultades financieras, cada peso debe tener nombre y apellido. Dejar transacciones en una categoría genérica como "Sin Clasificar" u "Otros" es el equivalente a dejar la puerta de la casa abierta por la noche: no sabes qué se está saliendo por ahí. Si la suma de estos gastos es alta, significa que tienes una fuga invisible de dinero que no estás controlando.

### 📝 Enunciado
Calcula cuánto dinero total se ha ido en la categoría `"Sin Clasificar"` (que asignamos en la limpieza a los valores nulos). Determina también qué porcentaje representa este monto respecto al gasto total real de tu historial (excluyendo los registros iniciales pero manteniendo tus categorías de gasto).

### 💡 Pistas de Pandas

<details>
1. **Para calcular el gasto total real:** Puedes usar la suma de la columna `['Monto']` del DataFrame filtrado que creaste en el Ejercicio 1 (`df_gastos_reales`).
2. **Para filtrar la categoría específica:** Selecciona las filas de `df_gastos_reales` donde la columna `Categoría` sea exactamente igual a `'Sin Clasificar'` y aplica `.sum()` a la columna `['Monto']`.
3. **Para el porcentaje:** Divide el total de "Sin Clasificar" entre el gasto total real y multiplícalo por 100.
</details>

In [47]:
#1. Calculo el total de los gastos
total_gastos = df_gastos_reales['Monto'].sum()
total_gastos = total_gastos * -1
print(f'El total de gastos es: {total_gastos:2f}')

El total de gastos es: 119092572.680000

In [48]:
#2. Filtrar categoria 'Sin clasificar' y sumar el monto
monto_gastos_sin_clasificar = df_gastos_reales[df_gastos_reales['Categoría'] == 'Sin Clasificar']['Monto'].sum()
print(f'El total de gastos sin clasificar es: {monto_gastos_sin_clasificar}')

El total de gastos sin clasificar es: 0.0

In [49]:
#Calcular el porcentaje de gastos sin clasificar
porcen = monto_gastos_sin_clasificar / total_gastos
print(f'El % de gastos sin clasificar es: {porcen}')

El % de gastos sin clasificar es: 0.0

<details>
<summary>Conclusión del Diagnóstico Financiero</summary>

1. Cero Fugas Invisibles: El resultado de 0.0 COP en gastos Sin Clasificar demuestra que eres sumamente ordenado con tus registros. Sabemos exactamente a dónde va cada peso, lo que significa que el problema no es que el dinero se esfume sin saberlo, sino las decisiones de compra conscientes que estás tomando.
2. El Verdadero Peso de tu Presupuesto: Al limpiar el ruido de los favores y las deudas pesadas, descubrimos que tus dos mayores salidas de dinero reales son Mercado (15.6 millones de COP) y Gadgets y accesorios (14.7 millones de COP).
	• La mirada franca: Gastar casi 15 millones en tecnología y accesorios es un lujo insostenible cuando se arrastran deudas severas. Ese dinero hoy podría estar amortizando tu tarjeta de crédito o tu libranza.

</details>

# 🛠️ Ejercicio 3: Radiografía de los Métodos de Pago

### 📌 Contexto Financiero
A veces el problema no es solo "en qué" gastamos, sino "con qué" pagamos. El uso descontrolado de tarjetas de crédito o cupos de financiamiento crea una ilusión de liquidez que termina alimentando deudas con intereses altísimos (como la tarjeta de Davivienda de 10 millones que vimos al inicio). Necesitamos identificar de cuál de tus cuentas o bolsillos está saliendo la mayor cantidad de dinero real para saber a qué billetera hay que ponerle un freno de mano urgente.

### 📝 Enunciado
Utilizando el `df_gastos_reales`, agrupa las transacciones por la columna `Cuenta`. Calcula la suma total de los montos para cada una y ordena los resultados de mayor a menor gasto para descubrir qué cuenta o tarjeta está canalizando la mayor parte de tus salidas de dinero cotidianas.


### 💡 Pistas de Pandas

<details>

1. **Para agrupar y ordenar:** Aplica una estructura muy similar a la del Ejercicio 1. Usa `.groupby.  ('Columna_Cuenta')`, selecciona la columna `['Monto']`, calcula su `.sum()` y ordénalo con `.sort_values(ascending=True)` para que las cuentas con salidas más grandes (números más negativos) queden arriba.      

2. **Interpretación:** Observa con atención los nombres de las cuentas que aparecen en la cima de la lista.
</details>

In [50]:
df_gastos_reales.groupby('Cuenta')['Monto'].sum().abs().sort_values(ascending=False)

Cuenta
Cuenta Davivienda                  67688554.81
TC Visa Davivienda                 23690808.00
Efectivo                            9084900.00
TC Mastercard Black Bancolombia     5397272.11
ADDI                                4352760.00
Cuenta Bancolombia                  3553778.00
Bolsillo Pago TC                    3371721.00
Bolsillo Fondo Tranquilidad         1373600.00
Bolsillo Nando/Cris                  253327.00
Libre inversión Davi                 138056.45
Subsidios Cami                        69000.00
Bolsillo Personal                     61000.00
Libranza Davivienda                   41408.31
Ahorro Fonal                          16387.00
Name: Monto, dtype: float64

## Conclusiones Crudas y Sinceras: El Diagnóstico del Ejercicio 3

<details>

1. **La Falsa Ilusión del Plástico y la Deuda Ágil (\$33.4M COP):** 
   Aunque creas que solo tienes una tarjeta de crédito (Davivienda), tus datos revelan que operás con TRES vehículos de deuda corriente activos: `TC Visa Davivienda`, `TC Mastercard Black Bancolombia` (que puede estar asociada a una cuenta o ser un cupo) y `ADDI`. Sumar más de 33 millones de pesos gastados a través de estos canales es la prueba matemática de que **estás viviendo un estilo de vida que tus ingresos reales no pueden pagar**. Usar ADDI (financiamiento rápido) es el síntoma definitivo de que estás usando deuda para cubrir la falta de liquidez inmediata.

2. **La Hemorragia del Efectivo (\$9.08M COP):**
   Nueve millones de pesos quemados en efectivo es una cifra alarmante para alguien en crisis. El efectivo es el "dinero invisible": se deshace en billetes de \$10.000 y \$20.000 en la calle. Si estás en dificultades financieras, **el efectivo debe ser severamente restringido**, porque es el canal donde la fuerza de voluntad claudica más fácil.

3. **20 Años de Repetición (El "Modo Esclavo" del Banco):**
   Tus salidas están lideradas por `Cuenta Davivienda` (67.6M COP), pero inmediatamente después vienen tus deudas cotidianas. Estás atrapado en un ciclo donde trabajas para pagar la tarjeta, te quedas sin efectivo, vuelves a usar la tarjeta para el mercado o los gadgets, y vuelves a empezar. Si llevas 20 años así, es porque **sigues usando los mismos métodos esperando un resultado diferente**. La tarjeta de crédito y los cupos de financiamiento como ADDI tienen que ser cancelados, congelados o destruidos. No eres una persona apta para usar tarjetas de crédito en este momento de tu vida.

4. **El Freno de Mano Urgente:**
   Para romper un ciclo de 20 años de deudas, la primera regla es: **"Si estás en un hoyo, deja de cavar"**. Cada vez que pasas la tarjeta de Davivienda o pides un crédito en ADDI para comprar algo que no es comida o salud, estás decidiendo voluntariamente prolongar tu crisis un año más.

</details>

# 🛠️ Ejercicio 4: El Índice de Gasto Discrecional (Deseos vs. Necesidades)

### 📌 Contexto Financiero
Cuando se llevan 20 años acumulando deudas, el cerebro se acostumbra a normalizar ciertos gastos, convenciéndonos de que son "necesarios". Para romper el ciclo, debemos clasificar tus gastos con total frialdad en dos grupos: **Supervivencia** (Arriendo, Servicios públicos, Salud, Mercado básico) y **Deseo/Estilo de Vida** (Estadio, Mecato, Gadgets, Entretenimiento, Restaurantes). Si tu gasto en "Deseos" es alto mientras estás en crisis, estás saboteando activamente tu propia libertad financiera.

### 📝 Enunciado
Crea una lista con las categorías que representan "Deseos o Estilo de Vida" (por ejemplo: `Gadgets y accesorios`, `Restaurantes`, `Entretenimiento`, `Mecato`, `Estadio`, `Regalos`, `Apps/suscripciones`). Filtra tu `df_gastos_reales` para calcular cuánto dinero suman estas categorías en total y qué porcentaje representan del total de tus gastos reales.

### 💡 Pistas de Pandas
 <details>

1. **Para filtrar por una lista de categorías:** Crea una lista de Python con los nombres exactos de las categorías de lujos: `lista_lujos = ['Mecato', 'Estadio', ...]`.
2. **Usa el método `.isin()`:** Filtra tu DataFrame aplicando la condición: `df_gastos_reales[df_gastos_reales['Categoría'].isin(lista_lujos)]`.
3. **Suma y compara:** Calcula la suma de la columna `['Monto']` para esta selección, aplícale `.abs()` y divídela entre el `total_gastos` que hallaste en el Ejercicio 2 para sacar el porcentaje de dinero que se está yendo en "deseos".

</details>

In [51]:
#Creo la lista
list_estilo_vida = ['Gadgets y accesorios', 'Restaurantes', 'Entretenimiento', 'Mecato', 'Estadio', 'Regalos', 'Apps/suscripciones']

#Filtrar y calcular la suma de los gastos de la lista estilo de vida

total_estilo_vida = df_gastos_reales[df_gastos_reales['Categoría'].isin(list_estilo_vida)]['Monto'].abs().sum()

#Calcular porcentaje

porcen_estilo_vida = total_estilo_vida / total_gastos * 100

# Primer print: Formato de moneda con separador de miles y sin decimales (común en COP)
print(f'El valor total de gastos de estilo de vida es: ${total_estilo_vida:,.0f} COP')

# Segundo print: Con exactamente 2 decimales para el porcentaje
print(f'El % de gastos de estilo de vida es: {porcen_estilo_vida:.2f}%')

El valor total de gastos de estilo de vida es: $20,794,651 COP
El % de gastos de estilo de vida es: 17.46%

### 🚨 Conclusiones Crudas y Sinceras: El Índice de Gasto Discrecional

<details>

1. **La Financiación de una Falsa Realidad ($20.794.651 COP):**
   Has gastado casi 21 millones de pesos en lujos, antojos y entretenimiento (estadio, mecato, gadgets) mientras arrastras una deuda de libranza de más de 63 millones y más de 10 millones en la tarjeta de crédito. Financieramente, esto es una conducta de auto-saboteo destructiva. Estás priorizando la gratificación instantánea (el placer de hoy) a costa de tu tranquilidad del mañana. Esos 20.7 millones habrían liquidado por completo tu tarjeta de crédito Davivienda dos veces.

2. **El Mito del "No me alcanza el dinero" (17.46%):**
   Casi el 18% de todo lo que gastas se va en cosas que podrías eliminar mañana mismo sin poner en riesgo tu supervivencia. Esto tumba por completo el argumento de "tengo dificultades porque gano poco" o "la vida está muy cara". Tienes un margen de maniobra de casi una quinta parte de tus gastos. No estás atrapado por falta de ingresos; estás atrapado porque estás usando tus ingresos para financiar un estilo de vida que no te corresponde tener en este momento.

3. **El Costo Real de tus Deseos (Intereses Compuestos):**
   Esos 20.7 millones de pesos no costaron eso. Al haber sido pagados en gran parte con tarjetas de crédito, ADDI o dejando de pagar deudas, les tienes que sumar la tasa de interés. Esos gadgets, salidas al estadio y comidas fuera de casa te están costando el doble o el triple debido a los intereses de la deuda que dejas de amortizar. Estás comprando cosas baratas a plazos extremadamente caros.

4. **Plan de Acción Inmediato:**
   Si de verdad quieres romper un ciclo de 20 años de deudas, el bloque de "Estilo de Vida" debe reducirse a menos del 5% de tus gastos totales a partir del próximo mes. Ir al estadio se congela, los gadgets se prohíben, y el mecato se elimina. Estás en modo de emergencia económica.

</details>

# 🛠️ Ejercicio 5: El Cruce del Peligro (Lujos en Efectivo y Crédito)

### 📌 Contexto Financiero
Ya descubrimos el tamaño del bloque de lujos (\$20.7M). Ahora necesitamos saber cómo los estás pagando. Si estás usando efectivo para estos antojos, es dinero que sacas del cajero y se desvanece sin control. Si estás usando las tarjetas de crédito o ADDI, estás pagando intereses altísimos por cosas que se consumen en un día (comida, entretenimiento). Necesitamos ver la distribución de tus lujos por cuenta.

### 📝 Enunciado
Toma el subconjunto de datos de tus gastos de estilo de vida (las filas que contienen tus lujos) y agrúpalas por la columna `Cuenta`. Suma los montos en valor absoluto y ordénalos de mayor a menor para ver cuál billetera o tarjeta es la que más financia tus deseos.

### 💡 Pistas de Pandas
<details>

1. **Filtro base:** Puedes reutilizar el filtro del ejercicio anterior: `df_lujos = df_gastos_reales[df_gastos_reales['Categoría'].isin(list_estilo_vida)]`.
2. **Agrupación:** Sobre ese `df_lujos`, aplica un `.groupby('Cuenta')['Monto'].sum().abs().sort_values(ascending=False)`.

</details>

In [54]:
#Creo el df de gastos estilo de vida
df_gastos_estilo_vida = df_gastos_reales[df_gastos_reales['Categoría'].isin(list_estilo_vida)].copy()
df_gastos_estilo_vida.head()

#Agrupo por cuenta el df_gastos_estilo_vida
df_gastos_estilo_vida.groupby('Cuenta')['Monto'].sum().abs().sort_values(ascending=False)

Cuenta
TC Visa Davivienda                 12080844.0
Cuenta Davivienda                   3395007.0
Efectivo                            1937900.0
TC Mastercard Black Bancolombia     1263900.0
ADDI                                1251000.0
Bolsillo Fondo Tranquilidad          500000.0
Bolsillo Nando/Cris                  230000.0
Subsidios Cami                        51000.0
Bolsillo Personal                     45000.0
Bolsillo Pago TC                      40000.0
Name: Monto, dtype: float64

### 🚨 Conclusiones Crudas y Sinceras: El Cruce del Peligro (Financiando Lujos)
<details>

1. **La Tragedia de las Tarjetas: Comprando Placer a Cuotas (\$13.3M COP):**
   Tu peor enemigo financiero está identificado: la `TC Visa Davivienda` (12M COP) y la `TC Mastercard Black Bancolombia` (1.2M COP) financiaron más del 64% de tus caprichos. Pasar el plástico para comprar gadgets, comer fuera o ir al estadio es una aberración financiera cuando estás en crisis. Estás pagando tasas de usura por cosas que no te generan un solo peso de retorno. Esos 13.3 millones en tarjetas hoy te están cobrando intereses sobre intereses, hundiendo tu flujo de caja mes a mes.

2. **La Trampa de ADDI (\$1.25M COP):**
   Gastar 1.25 millones de pesos en lujos a través de ADDI es el síntoma de una adicción al consumo. ADDI te facilita comprar lo que no te alcanza con dinero real bajo la falsa promesa de "cuotas fáciles". Financieramente, esto es aceptar que no tienes control de tus impulsos: si no tienes la plata en tu cuenta de ahorros para comprar un gadget o un antojo, simplemente NO debes comprarlo.

3. **El Auto-Saboteo del Ahorro (\$730.000 COP):**
   Es doloroso ver que usaste el `Bolsillo Fondo Tranquilidad` (\$500.000) y el `Bolsillo Nando/Cris` (\$230.000) para pagar lujos. El fondo de tranquilidad es para emergencias (salud, desempleo), no para financiar estilo de vida. Vaciar tus ahorros de seguridad para darte un gusto es dejarte desprotegido ante cualquier imprevisto real, obligándote a volver a usar las tarjetas de crédito mañana.

4. **El Efectivo Invisible (\$1.93M COP):**
   Casi 2 millones de pesos en efectivo se esfumaron en lujos sin que te dieras cuenta. Al no pasar por el banco, este dinero se drena en billetes pequeños de manera silenciosa, debilitando tu capacidad de pago para las deudas reales.

</details>

# 🛠️ Ejercicio 6: El Calendario del Gasto (Evolución Mensual)

### 📌 Contexto Financiero
Para saber si tus hábitos financieros están cambiando o si sigues atrapado en la inercia de los últimos 20 años, necesitamos ver los datos de manera cronológica. Al agrupar tus gastos reales por mes y año, descubriremos si tus salidas de dinero están disminuyendo gracias a un esfuerzo de contención, o si estás manteniendo un nivel de gasto críticamente alto mes a mes de forma sostenida.

### 📝 Enunciado
Extrae el período (Mes y Año) a partir de la columna `Fecha` de tu `df_gastos_reales`. Agrupa los gastos totales por este nuevo período cronológico, calcula la suma en valor absoluto y muestra la evolución de tus salidas de dinero en el tiempo ordenadas cronológicamente.

### 💡 Pistas de Pandas
<details>

1. **Para extraer el mes y año:** Puedes usar el accesor de fechas `.dt.to_period('M')` sobre la columna `Fecha` para crear una nueva columna llamada `Mes`. Ejemplo: `df_gastos_reales['Mes'] = df_gastos_reales['Fecha'].dt.to_period('M')`.
2. **Agrupación cronológica:** Agrupa por esta nueva columna `['Mes']`, selecciona `['Monto']`, aplica el `.sum()`, luego `.abs()` y finalmente ordena por el índice cronológico con `.sort_index()`.

</details>

In [56]:
#Extraer mes y año
df_gastos_reales['Mes'] = df_gastos_reales['Fecha'].dt.to_period('M')
df_gastos_reales

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota,Mes
9,2026-01-20,Gastos,-7840.0,COP,Gastos financieros,TC Visa Davivienda,NaN,Comisión avance,2026-01
11,2026-01-20,Gastos,-69000.0,COP,Salud,Cuenta Davivienda,NaN,Cita optometria,2026-01
12,2026-01-20,Gastos,-50000.0,COP,Gadgets y accesorios,Efectivo,NaN,Hideogel 17 Pro Max,2026-01
13,2026-01-21,Gastos,-65000.0,COP,Gadgets y accesorios,Efectivo,NaN,Case space Protector cámaras,2026-01
14,2026-01-22,Gastos,-87300.0,COP,Regalos,TC Visa Davivienda,NaN,Cumpleaños Cami,2026-01
...,...,...,...,...,...,...,...,...,...
1073,2026-10-30,Gastos,-111700.0,COP,Seguros,Cuenta Davivienda,NaN,Aporte pensión,2026-10
1076,2026-10-30,Gastos,-872476.0,COP,Pago bancos y deudas,Cuenta Davivienda,NaN,Cuota Libranza Davivienda,2026-10
1077,2026-10-30,Gastos,-111700.0,COP,Salud,Cuenta Davivienda,NaN,Aporte salud,2026-10
1078,2026-10-30,Gastos,-5300.0,COP,Restaurante empresa,Cuenta Davivienda,NaN,Deducción alimentaria,2026-10
1080,2026-10-30,Gastos,-8108.0,COP,Seguros,Cuenta Davivienda,NaN,Prever,2026-10

In [60]:
#Agrupar suma de gastos por mes
df_gastos_reales.groupby('Mes')['Monto'].sum().abs().sort_index()

Mes
2026-01     5570781.00
2026-02     8856900.00
2026-03     8669616.51
2026-04    13258086.00
2026-05    13409578.11
2026-06    12895785.00
2026-07    16348493.61
2026-08    23302830.00
2026-09    10040650.00
2026-10     6739852.45
Freq: M, Name: Monto, dtype: float64

### 🚨 Conclusiones Crudas y Sinceras: El Calendario del Gasto (Evolución Mensual)

<details>

1. **La Curva del Desastre: Una Crisis en Ascenso Violento:**
   Tu año comenzó en enero con un gasto de 5.5 millones de COP. Sin embargo, en lugar de contener el dinero, tus salidas aumentaron de forma descontrolada mes a mes hasta tocar un techo aterrador en **agosto con más de 23.3 millones de COP** gastados en un solo mes. Esto demuestra que tu patrón de endeudamiento y gasto no es estático: venías en una espiral acelerada donde cada mes necesitabas cavar un hoyo más profundo para sostener tu ritmo de vida.

2. **El Espejismo de la "Mejora" en Septiembre y Octubre:**
   Vemos una caída fuerte en septiembre (10M COP) y octubre (6.7M COP). Aunque visualmente parece un alivio, financieramente debes tener mucho cuidado. Como cortamos los gastos futuros y omitimos deudas cruzadas, esta bajada puede significar dos cosas: o te quedaste completamente sin cupo en las tarjetas de crédito y el banco te frenó a la fuerza, o por fin empezaste a restringir las compras. Si fue por control propio, vas por buen camino; si fue porque los bancos te cerraron el grifo, estás en el punto de máxima vulnerabilidad.

3. **La Insostenibilidad Matemática:**
   Pasar de promediar 8 millones a principios de año a promediar más de 14 millones entre abril y agosto explica por qué colapsó tu flujo de caja. Ninguna economía personal resiste que sus gastos corrientes se dupliquen o tripliquen en cuestión de meses si los ingresos se mantienen iguales.

</details>

# 🛠️ Ejercicio 7: Días de Peligro Financiero

### 📌 Contexto Financiero
Muchas personas en crisis gastan por impulso o por "recompensa". El cerebro sabotea las finanzas con pensamientos como *"Trabajé duro toda la semana, me lo merezco"*. Al agrupar tus gastos reales por los días de la semana, descubriremos si tu crisis financiera se alimenta de la rutina diaria o si son los fines de semana (viernes a domingo) donde pierdes por completo el control de tu dinero.

### 📝 Enunciado
Extrae el día de la semana a partir de la columna `Fecha` de tu `df_gastos_reales` (puedes extraer el nombre del día o el número de 0 a 6). Agrupa tus gastos totales por este día, calcula la suma en valor absoluto y ordena el resultado para identificar cuál es el día más peligroso para tu bolsillo.

### 💡 Pistas de Pandas
<details>

1. **Para extraer el nombre del día en texto:** Puedes usar el accesor de fechas `.dt.day_name()`. Ejemplo: `df_gastos_reales['Dia_Semana'] = df_gastos_reales['Fecha'].dt.day_name()`.
2. **Agrupación:** Agrupa por esta nueva columna, selecciona `['Monto']`, aplica el `.sum().abs()` y ordénalo con `.sort_values(ascending=False)` para ver el día con mayor gasto en la cima.
</details>

In [105]:
#Extraer día de la semana
df_gastos_reales['Dia_Semana'] = df_gastos_reales['Fecha'].dt.day_name()
df_gastos_reales.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota,Mes,Dia_Semana
9,2026-01-20,Gastos,"-7,840",COP,Gastos financieros,TC Visa Davivienda,NaN,Comisión avance,2026-01,Tuesday
11,2026-01-20,Gastos,"-69,000",COP,Salud,Cuenta Davivienda,NaN,Cita optometria,2026-01,Tuesday
12,2026-01-20,Gastos,"-50,000",COP,Gadgets y accesorios,Efectivo,NaN,Hideogel 17 Pro Max,2026-01,Tuesday
13,2026-01-21,Gastos,"-65,000",COP,Gadgets y accesorios,Efectivo,NaN,Case space Protector cámaras,2026-01,Wednesday
14,2026-01-22,Gastos,"-87,300",COP,Regalos,TC Visa Davivienda,NaN,Cumpleaños Cami,2026-01,Thursday

In [106]:
#Agrupar por dia y sumar el monto
df_gastos_reales.groupby('Dia_Semana')['Monto'].sum().abs().sort_values(ascending=False).reset_index()

  Dia_Semana      Monto
0     Friday 44,801,094
1    Tuesday 20,127,825
2  Wednesday 14,037,832
3   Thursday 13,984,237
4   Saturday 10,520,367
5     Monday  9,819,383
6     Sunday  5,801,835

### 🚨 Conclusiones Crudas y Sinceras: Días de Peligro Financiero
<details>

1. **El "Viernes Negro" Constante (\$44.8M COP):**
   El viernes no es solo tu día de mayor gasto; es una catástrofe financiera absoluta. Has gastado **más de 44.8 millones de pesos en viernes**, lo que equivale a casi el doble de lo que gastas en cualquier otro día de la semana. El viernes representa el fin de la jornada laboral y el inicio del descanso, lo que abre la puerta al gasto por impulso, salidas, compras de gadgets y antojos bajo la premisa de "me lo merezco". Tu fin de semana financiero empieza el viernes y es ahí donde tu fuerza de voluntad colapsa por completo.

2. **El Misterio y Peligro de los Martes (\$20.1M COP):**
   Llama poderosamente la atención que el martes ocupe el segundo lugar con más de 20 millones de pesos. Al ser un día laboral a mitad de semana, esto suele estar amarrado a pagos fijos automatizados, debitos directos de deudas, o compras pesadas programadas que realizas ese día. Si no son deudas, significa que estás teniendo picos de ansiedad o compras a mitad de semana que debes vigilar de cerca.

3. **El Fin de Semana Curiosamente Bajo (\$16.3M COP combinados):**
   El sábado (\$10.5M) y el domingo (\$5.8M) registran montos significativamente menores que el viernes. Esto nos dice que el golpe fuerte al bolsillo ocurre apenas recibes liquidez o apenas se abre el fin de semana (el viernes). No dejas que el dinero llegue al sábado; lo quemas el mismo viernes.

</details>

# 🛠️ Ejercicio 8: Balance de Emergencia (Ingresos vs. Gastos Netos)

### 📌 Contexto Financiero
Para ponerle fin a 20 años de deudas, la última prueba matemática es medir tu Flujo de Caja Neto. Si tus gastos cotidianos superan a tus ingresos cotidianos, significa que estás operando en déficit (pérdidas), y que estás usando las tarjetas de crédito y los préstamos para subsidiar tu día a día. Necesitamos ver la verdad desnuda de cuánta plata entra contra cuánta plata sale.

### 📝 Enunciado
Toma tu DataFrame original limpio (el que contiene tanto `Ingresos` como `Gastos` pero sin los "Registros iniciales") filtrado hasta el 31 de octubre de 2026. Agrupa los datos por la columna `Tipo` y calcula la suma total para comparar tus Ingresos contra tus Gastos Totales Reales en el año.

### 💡 Pistas de Pandas
<details>

1. **Filtro base:** Asegúrate de usar un DataFrame que excluya los registros que contengan "Registro inicial" tanto de egreso como de ingreso, y que esté recortado a fechas menores o iguales al `2026-10-31`.
2. **Agrupación final:** Agrupa por la columna `Tipo`, selecciona `['Monto']` y aplica el `.sum()`. Aquí mantén los signos originales (ingresos positivos, gastos negativos) para ver la diferencia neta de forma directa.
</details>

In [107]:
#Debo crear el df de todos los registros pero excluyedo los Registros Iniciales y solo registros hasta 2026-10-31
df_sin_registros_iniciales = df_data[(df_data['Fecha'] <= '2026-10-31') & ~(df_data['Categoría'] == 'Registro inicial egreso')].copy()
df_sin_registros_iniciales.head()

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota
0,2026-01-19,Ingresos,"76,026",COP,Registro inicial ingreso,Bolsillo Moto,NaN,Registro inicial
1,2026-01-19,Ingresos,"29,500",COP,Registro inicial ingreso,Bolsillo Fondo Tranquilidad,NaN,Registro inicial
2,2026-01-19,Ingresos,"200,000",COP,Registro inicial ingreso,Bolsillo Nando/Cris,NaN,Registro inicial
3,2026-01-19,Ingresos,"254,000",COP,Registro inicial ingreso,Efectivo,NaN,Registro inicial
7,2026-01-19,Ingresos,"1,803,425",COP,Registro inicial ingreso,Ahorro Fonal,NaN,Registro inicial

In [108]:
# Configurar Pandas para mostrar números flotantes con separadores de miles y sin decimales
pd.options.display.float_format = '{:,.0f}'.format

#Agrupar df_sin_registros_iniciales por Tipo y calcular el total
df_sin_registros_iniciales.groupby('Tipo')['Monto'].sum()

Tipo
Gastos          -121,276,290
Ingresos         125,101,481
Transferencia     50,224,875
Name: Monto, dtype: float64

In [109]:
#Voy a llevar a variables los ingresos,los gastos y calcular el superavit

#Gastos
gastos = df_sin_registros_iniciales[df_sin_registros_iniciales['Tipo'] == 'Gastos']['Monto'].sum()
print(f"El total real de gastos es: ${gastos:,.0f} COP")

#Ingresos
ingresos = df_sin_registros_iniciales[df_sin_registros_iniciales['Tipo'] == 'Ingresos']['Monto'].sum()
print(f"El total real de ingresos es: ${ingresos:,.0f} COP")

#Superavit
superavit = ingresos + gastos
print(f"El superavit real es: ${superavit:,.0f} COP")

El total real de gastos es: $-121,276,290 COP
El total real de ingresos es: $125,101,481 COP
El superavit real es: $3,825,192 COP

### 🚨 Conclusiones Crudas y Sinceras: Balance de Emergencia (La Trampa del Margen Falso)

<details>

1. **La Mentira del Superávit ($3.825.200 COP):**
   A primera vista, tu consola dice que te "sobraron" \$3.8 millones de pesos este año (ingresaste 125M y gastaste 121M). Financieramente, esto es un espejismo letal. Si te hubiera sobrado ese dinero real en efectivo, no tendrías dificultades financieras ni estarías acumulando deudas. Esos 3.8 millones de margen positivo son ficticios porque gran parte de tus "gastos" cotidianos se pagaron con las tarjetas de crédito o ADDI, y no con el dinero real de tus ingresos.

2. **Viviendo al Filo de la Navaja (Gasto del 96.9%):**
   Estás gastando el 96.9% de todo lo que ingresas. No tienes absolutamente ningún margen de maniobra para imprevistos. Cualquier daño en la moto, cualquier consulta médica o cualquier gasto extra te obliga inmediatamente a meter el tarjetazo porque te consumes hasta el último centavo que entra a tu cuenta.

3. **La Sentencia de los 20 Años:**
   Si ingresas 125 millones y te gastas 121 millones en el año, pero al mismo tiempo arrastras más de 77 millones en deudas (libranza, tarjetas, servicios), significa que **estás usando el cupo de los bancos para mantener un estilo de vida que tus ingresos reales no pueden soportar**. Trabajas para pagar deudas, te quedas sin efectivo, usas las tarjetas para vivir, y el ciclo se repite. Estás atrapado porque tu nivel de vida está calibrado al límite de tus ingresos, sin dejar espacio para pagar el pasado.

</details>

# 🛠️ Ejercicio 9: Radiografía Evolutiva de Pagos Bancarios (Mes a Mes)

### 📌 Contexto Financiero
Auditar un solo mes nos dice qué falló hoy, pero analizar los pagos bancarios mes a mes nos revela la tendencia del endeudamiento. Si los pagos a los bancos crecen mes a mes, significa que la bola de nieve de las deudas se está acelerando. Necesitamos ver cómo se distribuyeron las salidas de la categoría "Pago bancos y deudas" a lo largo de todo el año 2026.

### 📝 Enunciado
Filtra el DataFrame para aislar todas las transacciones de la categoría `"Pago bancos y deudas"`. Con estos datos, genera una matriz mensual que muestre la suma de los montos en valor absoluto, desglosada por cada mes del año (`Mes`) y clasificada por la `Cuenta` o la `Nota` que generó el desembolso.

### 💡 Pistas de Pandas
<details>

1. **index (Las Filas):** Es la variable que quieres ver de arriba hacia abajo en el extremo izquierdo. En tu caso, queremos ver las cuentas o deudas: `Cuenta`.

2. **columns (Las Columnas):** Es la variable que quieres que se desfile de izquierda a derecha en la parte superior. En tu caso, la línea de tiempo: `Mes`.

3. **values (Los Valores):** Es la columna numérica que se va a repartir dentro de la cuadrícula de la matriz: `Monto`.

4. **aggfunc (La Operación):** Es la función matemática que va a procesar los valores. Como queremos acumular los pesos pagados, usamos la suma: `sum`.


**Estructura Python**:  

DataFrame.pivot_table(index='Fila', columns='Columna', values='Monto_Numérico', aggfunc='Operación')


</details>

In [ ]:
#Crear df solo pagos bancos con el df_gastos_reales que es donde he calculado las fechas
df_pagos_bancos = df_gastos_reales[df_gastos_reales['Categoría'] == 'Pago bancos y deudas'].copy()

df_pagos_bancos.head(5)

,Fecha,Tipo,Monto,Moneda,Categoría,Cuenta,Contracuenta,Nota,Mes,Dia_Semana
42,2026-01-30,Gastos,"-60,063",COP,Pago bancos y deudas,Cuenta Davivienda,NaN,Cuota préstamo SN,2026-01,Friday
46,2026-01-30,Gastos,"-872,476",COP,Pago bancos y deudas,Cuenta Davivienda,NaN,Cuota Libranza Davivienda,2026-01,Friday
60,2026-02-01,Gastos,"-84,209",COP,Pago bancos y deudas,Cuenta Bancolombia,NaN,Abono TC,2026-02,Sunday
61,2026-02-01,Gastos,"-144,289",COP,Pago bancos y deudas,Cuenta Bancolombia,NaN,Abono TC,2026-02,Sunday
83,2026-02-13,Gastos,"-872,476",COP,Pago bancos y deudas,Cuenta Davivienda,NaN,Cuota Libranza Davivienda,2026-02,Friday

In [115]:
#Crear la tabla pivote
df_pagos_bancos.pivot_table(index='Cuenta', columns='Mes', values='Monto', aggfunc=sum).abs().fillna('-')

Mes,2026-01,2026-02,2026-03,2026-04,2026-05,2026-06,2026-07,2026-08,2026-09,2026-10
Cuenta,,,,,,,,,,
Bolsillo Pago TC,-,"1,078,518",-,"907,200",-,"194,206",-,-,"630,006",-
Cuenta Bancolombia,-,"228,498","572,480","2,450,242",-,-,-,-,-,-
Cuenta Davivienda,"932,539","2,026,485","2,799,469","4,902,701","4,830,661","6,504,755","7,388,973","15,000,639","3,115,153","3,980,104"

In [ ]:
#Sin pivot_table
df_pagos_bancos.groupby(['Cuenta', 'Mes'])['Monto'].sum().abs()

Cuenta              Mes
Bolsillo Pago TC    2026-02    1,078,518
                    2026-04      907,200
                    2026-06      194,206
                    2026-09      630,006
Cuenta Bancolombia  2026-02      228,498
                    2026-03      572,480
                    2026-04    2,450,242
Cuenta Davivienda   2026-01      932,539
                    2026-02    2,026,485
                    2026-03    2,799,469
                    2026-04    4,902,701
                    2026-05    4,830,661
                    2026-06    6,504,755
                    2026-07    7,388,973
                    2026-08   15,000,639
                    2026-09    3,115,153
                    2026-10    3,980,104
Name: Monto, dtype: float64

### 🚨 Conclusiones Crudas y Sinceras: La Auditoría Forense a Pagos Bancarios
<details>

1. **La Cuenta Davivienda está Secuestrada ($3,980,104 COP en Octubre):**
   El 100% del desfase en rojo que muestra la aplicación MoneyControl proviene de un drenaje directo en tu cuenta de ahorros principal. Tu cuenta no funciona como un vehículo de acumulación o paz mental; funciona como un pasadizo. El dinero entra el día de la quincena y sale disparado de inmediato a pagar mínimos, ADDI y obligaciones. Estás trabajando para el banco: el dinero solo toca tu cuenta unas horas antes de ser confiscado por tus deudas.

2. **La Huella Digital del Auto-Saboteo ($15,000,639 COP en Agosto):**
   Tu matriz de Pandas desnudó el momento exacto en que la crisis se profundizó. Los 15 millones que salieron de tu cuenta en agosto son la prueba matemática del crédito de Libre Inversión de $12 millones que solicitaste. Usaste deuda para tapar deudas, un comportamiento que llevas repitiendo 20 años. Ese pico en la gráfica es la evidencia de que cuando te sientes ahogado, tu salida de emergencia es cavar un hoyo más profundo con el sector bancario.

3. **La Desconexión Absoluta del Presupuesto:**
   Presupuestaste $2,800,000 COP en la aplicación para deudas, pero la realidad de tus obligaciones te obligó a desembolsar casi 4 millones. Estás viviendo bajo un presupuesto de "buenos deseos" que ignora el costo real de tus decisiones del pasado. Si no alineas los techos de tu aplicación con las cuotas reales que arroja Pandas, la barra siempre estará en rojo y seguirás viviendo al filo de la navaja.
   </details>

#  FIN