# 🚀 PROYECTO FINAL: Auditoría y Optimización de Retención de Clientes
🏢 El Caso de Negocio
Eres el Científico de Datos Principal de una gran tienda en línea. El Director Comercial está preocupado porque nota que hay desorden en los reportes mensuales: hay datos perdidos, clientes duplicados y la información de los envíos está en un archivo separado. Te ha entregado dos archivos CSV sucios y te pide consolidar una base de datos limpia para responder preguntas estratégicas de negocio.

## 📊**Los Datos (Copia y guarda estos bloques en tu nuevo cuaderno)**
Tabla 1: df_ventas (Información de transacciones y clientes)

csv. 
ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
1001, TechCorp ,Premium,12,1200.50,Norte
1002,AlphaLabs,Basico,4,450.00,Sur
1003,BetaOmega,Familiar,20,,Este
1001, TechCorp ,Premium,12,1200.50,Norte
1005,AlphaLabs,Basico,,250.00,Sur
1006,BetaOmega,Familiar,8,600.00,Este
1007,GlobalNet,Basico,2,150.00,
1008,DeltaSystems,Premium,15,1450.00,Oeste
1009,AlphaLabs,Basico,4,450.00,Sur
1010,GlobalNet,Familiar,25,950.00,Oeste
Usa el código con precaución.
Tabla 2: df_envios (Logística de entrega)


csv
ID_Pedido,Dias_Entrega,Estado_Envio
1001,3,Entregado
1002,5,Entregado
1003,7,Retrasado
1005,4,Entregado
1006,8,Retrasado
1007,2,Entregado
1008,3,Entregado
1010,6,Entregado

## 🎯 Lista de Control de Objetivos

- [ ] **Fase 1: Diagnóstico y Limpieza de Texto**
  - Detectar celdas vacías (`NaN`) en todo el dataset.
  - Remover espacios en blanco invisibles (al inicio/final) en la columna `Cliente`.
- [ ] **Fase 2: Auditoría de Clientes**
  - Identificar y eliminar filas duplicadas idénticas en `df_ventas`.
- [ ] **Fase 3: Imputación Estadística**
  - Calcular el promedio de la columna `Compras_2025`.
  - Rellenar los valores vacíos de esa columna con la media calculada.
- [ ] **Fase 4: Consolidación Multi-tabla**
  - Unir de forma horizontal (`merge`) la tabla de ventas con la de envíos.
  - Asegurar que no se pierda ningún pedido de la tabla principal (Left Join).
- [ ] **Fase 5: Reporte de Negocio**
  - Crear una tabla resumen agrupada por `Plan_Suscripcion`.
  - Mostrar la suma del `Total_Gastado_USD` y el promedio de `Compras_2025`.

In [39]:
import io
import pandas as pd


#crear los csv con código
csv_ventas = """ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
1001, TechCorp ,Premium,12,1200.50,Norte
1002,AlphaLabs,Basico,4,450.00,Sur
1003,BetaOmega,Familiar,20,,Este
1001, TechCorp ,Premium,12,1200.50,Norte
1005,AlphaLabs,Basico,,250.00,Sur
1006,BetaOmega,Familiar,8,600.00,Este
1007,GlobalNet,Basico,2,150.00,
1008,DeltaSystems,Premium,15,1450.00,Oeste
1009,AlphaLabs,Basico,4,450.00,Sur
1010,GlobalNet,Familiar,25,950.00,Oeste"""

csv_envios = """ID_Pedido,Dias_Entrega,Estado_Envio
1001,3,Entregado
1002,5,Entregado
1003,7,Retrasado
1005,4,Entregado
1006,8,Retrasado
1007,2,Entregado
1008,3,Entregado
1010,6,Entregado"""


#Crear los dataframes
df_ventas = pd.read_csv(io.StringIO(csv_ventas))
df_envios = pd.read_csv(io.StringIO(csv_envios))

In [40]:
#Mostrar los dataframes
df_ventas

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
0,1001,TechCorp,Premium,12.0,1200.5,Norte
1,1002,AlphaLabs,Basico,4.0,450.0,Sur
2,1003,BetaOmega,Familiar,20.0,NaN,Este
3,1001,TechCorp,Premium,12.0,1200.5,Norte
4,1005,AlphaLabs,Basico,NaN,250.0,Sur
5,1006,BetaOmega,Familiar,8.0,600.0,Este
6,1007,GlobalNet,Basico,2.0,150.0,NaN
7,1008,DeltaSystems,Premium,15.0,1450.0,Oeste
8,1009,AlphaLabs,Basico,4.0,450.0,Sur
9,1010,GlobalNet,Familiar,25.0,950.0,Oeste

In [41]:
#Mostrar los dataframes
df_envios

   ID_Pedido  Dias_Entrega Estado_Envio
0       1001             3    Entregado
1       1002             5    Entregado
2       1003             7    Retrasado
3       1005             4    Entregado
4       1006             8    Retrasado
5       1007             2    Entregado
6       1008             3    Entregado
7       1010             6    Entregado

## - [ ] **Fase 1: Diagnóstico y Limpieza de Texto**
  - Detectar celdas vacías (`NaN`) en todo el dataset.

In [42]:
#Detectar celdas vacías (`NaN`) en todo el dataset.
df_ventas.isnull().sum()

ID_Pedido            0
Cliente              0
Plan_Suscripcion     0
Compras_2025         1
Total_Gastado_USD    1
Region               1
dtype: int64

  - Remover espacios en blanco invisibles (al inicio/final) en la columna `Cliente`.

In [44]:
#Remover espacios en blanco invisibles (al inicio/final) en la columna `Cliente`.

#Buscar los espacios en blanco - Método 1 (El argumento na=False evita errores si tienes valores nulos o NaN en la columna).
df_ventas[df_ventas['Cliente'].str.contains(r"\s", na=False)]

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
0,1001,TechCorp,Premium,12.0,1200.5,Norte
3,1001,TechCorp,Premium,12.0,1200.5,Norte

In [46]:
#Buscar los espacios en blanco - Método 2
df_ventas[df_ventas['Cliente'].str.isspace() == True]

Empty DataFrame
Columns: [ID_Pedido, Cliente, Plan_Suscripcion, Compras_2025, Total_Gastado_USD, Region]
Index: []

In [47]:
#Remover los espacios en blanco
df_ventas['Cliente'] = df_ventas['Cliente'].str.strip()
df_ventas

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
0,1001,TechCorp,Premium,12.0,1200.5,Norte
1,1002,AlphaLabs,Basico,4.0,450.0,Sur
2,1003,BetaOmega,Familiar,20.0,NaN,Este
3,1001,TechCorp,Premium,12.0,1200.5,Norte
4,1005,AlphaLabs,Basico,NaN,250.0,Sur
5,1006,BetaOmega,Familiar,8.0,600.0,Este
6,1007,GlobalNet,Basico,2.0,150.0,NaN
7,1008,DeltaSystems,Premium,15.0,1450.0,Oeste
8,1009,AlphaLabs,Basico,4.0,450.0,Sur
9,1010,GlobalNet,Familiar,25.0,950.0,Oeste

In [49]:
#Comprobar nuevamente si hay espacios en blanco
df_ventas[df_ventas['Cliente'].str.contains(r"\s", na=False)]

Empty DataFrame
Columns: [ID_Pedido, Cliente, Plan_Suscripcion, Compras_2025, Total_Gastado_USD, Region]
Index: []

## - [ ] **Fase 2: Auditoría de Clientes**
  - Identificar y eliminar filas duplicadas idénticas en `df_ventas`.

In [52]:
#Identificar filas duplicadas identicas
df_ventas[df_ventas.duplicated()]

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
3,1001,TechCorp,Premium,12.0,1200.5,Norte

In [53]:
#Conservo los registros en un nuevo dataframe
df_clientes_duplicados = df_ventas[df_ventas.duplicated()]

#Mostrar nuevo dataframe
df_clientes_duplicados

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
3,1001,TechCorp,Premium,12.0,1200.5,Norte

In [54]:
#Eliminar los registros duplicados del dataframe original
df_ventas.drop_duplicates(inplace=True)

#Mostrar dataframe depurado
df_ventas

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
0,1001,TechCorp,Premium,12.0,1200.5,Norte
1,1002,AlphaLabs,Basico,4.0,450.0,Sur
2,1003,BetaOmega,Familiar,20.0,NaN,Este
4,1005,AlphaLabs,Basico,NaN,250.0,Sur
5,1006,BetaOmega,Familiar,8.0,600.0,Este
6,1007,GlobalNet,Basico,2.0,150.0,NaN
7,1008,DeltaSystems,Premium,15.0,1450.0,Oeste
8,1009,AlphaLabs,Basico,4.0,450.0,Sur
9,1010,GlobalNet,Familiar,25.0,950.0,Oeste

## - [ ] **Fase 3: Imputación Estadística**
  - Calcular el promedio de la columna `Compras_2025`.
  - Rellenar los valores vacíos de esa columna con la media calculada.

In [58]:
#Calcular la meedia de compras de 2025
media_compras = df_ventas['Compras_2025'].mean()
print(f'La media de compras de 2025 es: {media_compras}')

La media de compras de 2025 es: 11.25

In [62]:
#Asignar media a valores vacíos en columna Compras_2025
df_ventas['Compras_2025'] = df_ventas['Compras_2025'].fillna(media_compras)

df_ventas

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region
0,1001,TechCorp,Premium,12.00,1200.5,Norte
1,1002,AlphaLabs,Basico,4.00,450.0,Sur
2,1003,BetaOmega,Familiar,20.00,NaN,Este
4,1005,AlphaLabs,Basico,11.25,250.0,Sur
5,1006,BetaOmega,Familiar,8.00,600.0,Este
6,1007,GlobalNet,Basico,2.00,150.0,NaN
7,1008,DeltaSystems,Premium,15.00,1450.0,Oeste
8,1009,AlphaLabs,Basico,4.00,450.0,Sur
9,1010,GlobalNet,Familiar,25.00,950.0,Oeste

## - [ ] **Fase 4: Consolidación Multi-tabla**
  - Unir de forma horizontal (`merge`) la tabla de ventas con la de envíos.
  - Asegurar que no se pierda ningún pedido de la tabla principal (Left Join).

In [65]:
df_unificada = df_ventas.merge(df_envios, on= 'ID_Pedido', how='left')
df_unificada

,ID_Pedido,Cliente,Plan_Suscripcion,Compras_2025,Total_Gastado_USD,Region,Dias_Entrega,Estado_Envio
0,1001,TechCorp,Premium,12.00,1200.5,Norte,3.0,Entregado
1,1002,AlphaLabs,Basico,4.00,450.0,Sur,5.0,Entregado
2,1003,BetaOmega,Familiar,20.00,NaN,Este,7.0,Retrasado
3,1005,AlphaLabs,Basico,11.25,250.0,Sur,4.0,Entregado
4,1006,BetaOmega,Familiar,8.00,600.0,Este,8.0,Retrasado
5,1007,GlobalNet,Basico,2.00,150.0,NaN,2.0,Entregado
6,1008,DeltaSystems,Premium,15.00,1450.0,Oeste,3.0,Entregado
7,1009,AlphaLabs,Basico,4.00,450.0,Sur,NaN,NaN
8,1010,GlobalNet,Familiar,25.00,950.0,Oeste,6.0,Entregado

## - [ ] **Fase 5: Reporte de Negocio**
  - Crear una tabla resumen agrupada por `Plan_Suscripcion`.
  - Mostrar la suma del `Total_Gastado_USD` y el promedio de `Compras_2025`.

In [74]:
#.reset_index() quita la columna de agrupación como indice y la vuelve normal
df_unificada.groupby('Plan_Suscripcion')[['Total_Gastado_USD','Compras_2025']].agg({'Total_Gastado_USD': 'sum', 'Compras_2025': 'mean'}).reset_index()

  Plan_Suscripcion  Total_Gastado_USD  Compras_2025
0           Basico             1300.0      5.312500
1         Familiar             1550.0     17.666667
2          Premium             2650.5     13.500000

In [ ]:
#Exportar reporte como csv
'''
index=False: Es un argumento vital. Si no lo pones, Pandas guardará los números de las filas (0, 1, 2...) 
como una columna sin nombre en el archivo final, lo cual ensucia el documento.
'''
df_unificada.to_csv('reporte_retencion_clientes.csv', index=False)