# **Laboratorio plataforma de Streaming** #
Para este Laboratorio de Desafío, vamos a cambiar de ambiente. Ya no estamos en la tienda de tecnología. Ahora eres el Analista de Datos de una plataforma de Streaming (estilo Netflix o Spotify).

In [44]:
import pandas as pd

#Cargar df Streaming
df_streaming = pd.read_csv('/Users/nando/Ejercicios-Practica-Python/Ciencia de datos/Laboratorio Streaming/streaming.csv')
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
0,1,Ana_Gomez,Premium,65.0,3.0,Norte,15.99
1,2,Carlos_Perez,Basico,12.0,1.0,Sur,9.99
2,3,Mariana_Tech,Familiar,85.0,5.0,Este,22.99
3,4,Luis_G,Basico,45.0,2.0,Norte,9.99
4,5,Ana_Martínez,Premium,30.0,2.0,Sur,15.99
5,6,Juan_V,Familiar,110.0,4.0,Este,22.99
6,7,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
7,8,Pedro_S,Basico,8.0,1.0,Oeste,9.99
8,9,Carlos_Labs,Premium,42.0,3.0,Sur,15.99
9,10,Elena_M,Familiar,95.0,5.0,Norte,22.99
10,11,Luis_G,basico,45.0,2.0,Norte,9.99
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN
13,14,Andres_F,Basico,NaN,2.0,Sur,9.99
14,15,Camila_R,Premium,50.0,NaN,Oeste,15.99
15,16,Mateo_H,Familiar,120.0,6.0,Norte,22.99
16,17,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
17,18,Diego_S,Basico,5.0,1.0,Este,9.99
18,19,Valentina_M,Premium,75.0,3.0,NaN,15.99
19,20,Javier_A,Familiar,NaN,4.0,Sur,22.99
20,21,Andres_F,Basico,NaN,2.0,Sur,9.99
21,22,Laura_Q,Basico,18.0,1.0,Norte,9.99
22,23,Gabriel_P,Premium,60.0,3.0,Oeste,NaN
23,24,Isabella_Z,Familiar,105.0,5.0,Este,22.99
24,25,Lucas_W,Basico,22.0,NaN,Sur,9.99
25,26,Ana_Gomez,Premium,65.0,3.0,Norte,15.99
26,27,Nicolas_K,Premium,NaN,2.0,Norte,15.99
27,28,Daniela_O,Basico,14.0,1.0,NaN,9.99
28,29,Tomas_L,Familiar,88.0,4.0,Este,22.99
29,30,Martina_X,Premium,40.0,3.0,Oeste,15.99
30,31,Javier_A,Familiar,NaN,4.0,Sur,22.99
31,32,Samuel_V,Basico,9.0,1.0,Sur,9.99
32,33,Valeria_B,Premium,92.0,3.0,Norte,15.99
33,34,Benjamin_N,Familiar,130.0,5.0,Este,22.99
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN
35,36,Mia_P,Basico,31.0,2.0,Oeste,9.99
36,37,Joaquin_M,Premium,48.0,2.0,NaN,15.99
37,38,Elena_M,Familiar,95.0,5.0,Norte,22.99
38,39,Alejandro_C,Basico,11.0,1.0,Sur,9.99
39,40,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
40,41,Zoe_T,Premium,67.0,3.0,Norte,15.99
41,42,Matías_U,Familiar,NaN,4.0,Este,22.99
42,43,Victoria_I,Basico,25.0,2.0,Oeste,9.99
43,44,Carlos_Perez,Basico,12.0,1.0,Sur,9.99
44,45,Sara_E,Premium,58.0,3.0,Sur,15.99
45,46,Daniel_Y,Familiar,115.0,5.0,Norte,22.99
46,47,Simon_D,Basico,4.0,1.0,Este,9.99
47,48,Catalina_L,Premium,82.0,3.0,Oeste,15.99
48,49,Tomas_L,Familiar,88.0,4.0,Este,22.99
49,50,Amanda_F,Basico,NaN,1.0,Sur,9.99

## **🍿 Desafío 1: Filtro de Clientes VIP (Filtros Combinados)** ##
**Objetivo:** Filtra el DataFrame df_streaming para obtener los registros donde el Tipo_Suscripcion sea exactamente 'Premium' Y las Horas_Reproducidas sean estrictamente mayores a 50.

In [45]:
df_streaming[(df_streaming['Tipo_Suscripcion']== 'Premium') & (df_streaming['Horas_Reproducidas'] > 50 )]

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
0,1,Ana_Gomez,Premium,65.0,3.0,Norte,15.99
6,7,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
16,17,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
18,19,Valentina_M,Premium,75.0,3.0,NaN,15.99
22,23,Gabriel_P,Premium,60.0,3.0,Oeste,NaN
25,26,Ana_Gomez,Premium,65.0,3.0,Norte,15.99
32,33,Valeria_B,Premium,92.0,3.0,Norte,15.99
39,40,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
40,41,Zoe_T,Premium,67.0,3.0,Norte,15.99
44,45,Sara_E,Premium,58.0,3.0,Sur,15.99
47,48,Catalina_L,Premium,82.0,3.0,Oeste,15.99

### **🍿 Desafío 2: Búsqueda de texto parcial (.str.contains)** ###

**Contexto:** El departamento de seguridad detectó que algunas cuentas corporativas o institucionales se registraron con palabras clave en su nombre de usuario.

**Objetivo:** Filtra el DataFrame para encontrar los usuarios cuyo Nombre_Usuario contenga la palabra 'Tech' O la palabra 'Corp'.

In [46]:
df_streaming[(df_streaming['Nombre_Usuario'].str.contains('Tech', na=False))| (df_streaming['Nombre_Usuario'].str.contains('Corp', na=False))]

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
2,3,Mariana_Tech,Familiar,85.0,5.0,Este,22.99
6,7,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN
16,17,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN
39,40,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99

## **🍿 Desafío 3: Ordenamiento Jerárquico Complejo** ##

**Contexto:** El equipo de marketing quiere analizar el comportamiento de los usuarios organizados por regiones geográficas. Sin embargo, dentro de cada región, quieren identificar de inmediato a los usuarios que pasan más tiempo consumiendo contenido.

**Objetivo:** Ordena el DataFrame df_streaming por dos columnas al mismo tiempo: primero por Region_Usuario de forma alfabética (ascendente) y, segundo, por Horas_Reproducidas de mayor a menor (descendente).

In [47]:
df_streaming.sort_values(by=['Region_Usuario', 'Horas_Reproducidas'], ascending=[True,False])

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
33,34,Benjamin_N,Familiar,130.0,5.0,Este,22.99
5,6,Juan_V,Familiar,110.0,4.0,Este,22.99
23,24,Isabella_Z,Familiar,105.0,5.0,Este,22.99
28,29,Tomas_L,Familiar,88.0,4.0,Este,22.99
48,49,Tomas_L,Familiar,88.0,4.0,Este,22.99
2,3,Mariana_Tech,Familiar,85.0,5.0,Este,22.99
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN
17,18,Diego_S,Basico,5.0,1.0,Este,9.99
46,47,Simon_D,Basico,4.0,1.0,Este,9.99
41,42,Matías_U,Familiar,NaN,4.0,Este,22.99
15,16,Mateo_H,Familiar,120.0,6.0,Norte,22.99
45,46,Daniel_Y,Familiar,115.0,5.0,Norte,22.99
9,10,Elena_M,Familiar,95.0,5.0,Norte,22.99
37,38,Elena_M,Familiar,95.0,5.0,Norte,22.99
32,33,Valeria_B,Premium,92.0,3.0,Norte,15.99
40,41,Zoe_T,Premium,67.0,3.0,Norte,15.99
0,1,Ana_Gomez,Premium,65.0,3.0,Norte,15.99
25,26,Ana_Gomez,Premium,65.0,3.0,Norte,15.99
3,4,Luis_G,Basico,45.0,2.0,Norte,9.99
10,11,Luis_G,basico,45.0,2.0,Norte,9.99
21,22,Laura_Q,Basico,18.0,1.0,Norte,9.99
26,27,Nicolas_K,Premium,NaN,2.0,Norte,15.99
47,48,Catalina_L,Premium,82.0,3.0,Oeste,15.99
22,23,Gabriel_P,Premium,60.0,3.0,Oeste,NaN
6,7,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
16,17,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
39,40,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99
14,15,Camila_R,Premium,50.0,NaN,Oeste,15.99
29,30,Martina_X,Premium,40.0,3.0,Oeste,15.99
35,36,Mia_P,Basico,31.0,2.0,Oeste,9.99
42,43,Victoria_I,Basico,25.0,2.0,Oeste,9.99
7,8,Pedro_S,Basico,8.0,1.0,Oeste,9.99
44,45,Sara_E,Premium,58.0,3.0,Sur,15.99
8,9,Carlos_Labs,Premium,42.0,3.0,Sur,15.99
4,5,Ana_Martínez,Premium,30.0,2.0,Sur,15.99
24,25,Lucas_W,Basico,22.0,NaN,Sur,9.99
1,2,Carlos_Perez,Basico,12.0,1.0,Sur,9.99
43,44,Carlos_Perez,Basico,12.0,1.0,Sur,9.99
38,39,Alejandro_C,Basico,11.0,1.0,Sur,9.99
31,32,Samuel_V,Basico,9.0,1.0,Sur,9.99
13,14,Andres_F,Basico,NaN,2.0,Sur,9.99
19,20,Javier_A,Familiar,NaN,4.0,Sur,22.99
20,21,Andres_F,Basico,NaN,2.0,Sur,9.99
30,31,Javier_A,Familiar,NaN,4.0,Sur,22.99
49,50,Amanda_F,Basico,NaN,1.0,Sur,9.99
18,19,Valentina_M,Premium,75.0,3.0,NaN,15.99
36,37,Joaquin_M,Premium,48.0,2.0,NaN,15.99
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99
27,28,Daniela_O,Basico,14.0,1.0,NaN,9.99

## **🍿 Desafío 4: Ordenamiento Jerárquico Complejo** ##

**Contexto:** El equipo de retención de clientes quiere lanzar una campaña para reactivar a los usuarios que casi no entran a la plataforma. Necesitan identificar específicamente a las 4 cuentas con menor consumo.

**Objetivo:** Ordena el DataFrame según las Horas_Reproducidas de menor a mayor (ascendente) y quédate únicamente con los 4 primeros registros del resultado.

In [48]:
df_streaming.sort_values(by=['Horas_Reproducidas'], ascending=True).head(4)

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD
46,47,Simon_D,Basico,4.0,1.0,Este,9.99
17,18,Diego_S,Basico,5.0,1.0,Este,9.99
7,8,Pedro_S,Basico,8.0,1.0,Oeste,9.99
31,32,Samuel_V,Basico,9.0,1.0,Sur,9.99

## **🍿 Desafío 5: Reporte Ejecutivo Multimétrica (GROUP BY)** ##

**Contexto:** La dirección financiera necesita un informe rápido sobre los ingresos según el tipo de plan para evaluar la rentabilidad de las suscripciones.

**Objetivo:** Agrupa el DataFrame df_streaming por Tipo_Suscripcion, selecciona la columna Monto_Mensual_USD y obtén en una sola tabla el cobro más bajo ('min'), el cobro más alto ('max') y el total recaudado ('sum').

In [49]:
df_streaming.groupby('Tipo_Suscripcion')['Monto_Mensual_USD'].agg(['min', 'max', 'sum'])

                    min    max     sum
Tipo_Suscripcion
Basico             9.99   9.99  159.84
Familiar          22.99  22.99  298.87
Premium           15.99  15.99  255.84
basico             9.99   9.99    9.99
familiar            NaN    NaN    0.00
premium           15.99  15.99   15.99

## **🍿 Desafío 6: Operaciones matemáticas entre columnas** ##

**Contexto:** El departamento de operaciones quiere saber cuánto tiempo pasa un usuario conectado en promedio por cada dispositivo que tiene activo.

**Objetivo:** Crea una nueva columna llamada Horas_Por_Dispositivo que sea el resultado de dividir la columna Horas_Reproducidas entre la columna Dispositivos_Conectados.

In [50]:
df_streaming['Horas_Por_Dispositivo'] = df_streaming['Horas_Reproducidas'] / df_streaming['Dispositivos_Conectados']
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo
0,1,Ana_Gomez,Premium,65.0,3.0,Norte,15.99,21.666667
1,2,Carlos_Perez,Basico,12.0,1.0,Sur,9.99,12.000000
2,3,Mariana_Tech,Familiar,85.0,5.0,Este,22.99,17.000000
3,4,Luis_G,Basico,45.0,2.0,Norte,9.99,22.500000
4,5,Ana_Martínez,Premium,30.0,2.0,Sur,15.99,15.000000
5,6,Juan_V,Familiar,110.0,4.0,Este,22.99,27.500000
6,7,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99,13.750000
7,8,Pedro_S,Basico,8.0,1.0,Oeste,9.99,8.000000
8,9,Carlos_Labs,Premium,42.0,3.0,Sur,15.99,14.000000
9,10,Elena_M,Familiar,95.0,5.0,Norte,22.99,19.000000
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99,15.000000
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000
13,14,Andres_F,Basico,NaN,2.0,Sur,9.99,NaN
14,15,Camila_R,Premium,50.0,NaN,Oeste,15.99,NaN
15,16,Mateo_H,Familiar,120.0,6.0,Norte,22.99,20.000000
16,17,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99,13.750000
17,18,Diego_S,Basico,5.0,1.0,Este,9.99,5.000000
18,19,Valentina_M,Premium,75.0,3.0,NaN,15.99,25.000000
19,20,Javier_A,Familiar,NaN,4.0,Sur,22.99,NaN
20,21,Andres_F,Basico,NaN,2.0,Sur,9.99,NaN
21,22,Laura_Q,Basico,18.0,1.0,Norte,9.99,18.000000
22,23,Gabriel_P,Premium,60.0,3.0,Oeste,NaN,20.000000
23,24,Isabella_Z,Familiar,105.0,5.0,Este,22.99,21.000000
24,25,Lucas_W,Basico,22.0,NaN,Sur,9.99,NaN
25,26,Ana_Gomez,Premium,65.0,3.0,Norte,15.99,21.666667
26,27,Nicolas_K,Premium,NaN,2.0,Norte,15.99,NaN
27,28,Daniela_O,Basico,14.0,1.0,NaN,9.99,14.000000
28,29,Tomas_L,Familiar,88.0,4.0,Este,22.99,22.000000
29,30,Martina_X,Premium,40.0,3.0,Oeste,15.99,13.333333
30,31,Javier_A,Familiar,NaN,4.0,Sur,22.99,NaN
31,32,Samuel_V,Basico,9.0,1.0,Sur,9.99,9.000000
32,33,Valeria_B,Premium,92.0,3.0,Norte,15.99,30.666667
33,34,Benjamin_N,Familiar,130.0,5.0,Este,22.99,26.000000
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000
35,36,Mia_P,Basico,31.0,2.0,Oeste,9.99,15.500000
36,37,Joaquin_M,Premium,48.0,2.0,NaN,15.99,24.000000
37,38,Elena_M,Familiar,95.0,5.0,Norte,22.99,19.000000
38,39,Alejandro_C,Basico,11.0,1.0,Sur,9.99,11.000000
39,40,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99,13.750000
40,41,Zoe_T,Premium,67.0,3.0,Norte,15.99,22.333333
41,42,Matías_U,Familiar,NaN,4.0,Este,22.99,NaN
42,43,Victoria_I,Basico,25.0,2.0,Oeste,9.99,12.500000
43,44,Carlos_Perez,Basico,12.0,1.0,Sur,9.99,12.000000
44,45,Sara_E,Premium,58.0,3.0,Sur,15.99,19.333333
45,46,Daniel_Y,Familiar,115.0,5.0,Norte,22.99,23.000000
46,47,Simon_D,Basico,4.0,1.0,Este,9.99,4.000000
47,48,Catalina_L,Premium,82.0,3.0,Oeste,15.99,27.333333
48,49,Tomas_L,Familiar,88.0,4.0,Este,22.99,22.000000
49,50,Amanda_F,Basico,NaN,1.0,Sur,9.99,NaN

## **🍿 Desafío 7: Etiquetas condicionales binarias con np.where()** ##

**Contexto:** El equipo de marketing quiere segmentar a los usuarios según su nivel de consumo para una campaña.

**Objetivo:** Crea una nueva columna llamada Perfil_Consumo. Si el usuario tiene más de 60 Horas_Reproducidas, la columna debe registrar el texto 'Intenso'; de lo contrario, debe registrar 'Moderado'.

In [51]:
#importar numpy
import numpy as np

#Estructura: df_streaming['Nueva_Columna'] = np.where(df['Columna']condicion_logica, 'Valor_Si_Cumple', 'Valor_Si_No_Cumple')
df_streaming['Perfil_Consumo'] = np.where(df_streaming['Horas_Reproducidas'] > 60, 'Intenso','Moderado')
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo
0,1,Ana_Gomez,Premium,65.0,3.0,Norte,15.99,21.666667,Intenso
1,2,Carlos_Perez,Basico,12.0,1.0,Sur,9.99,12.000000,Moderado
2,3,Mariana_Tech,Familiar,85.0,5.0,Este,22.99,17.000000,Intenso
3,4,Luis_G,Basico,45.0,2.0,Norte,9.99,22.500000,Moderado
4,5,Ana_Martínez,Premium,30.0,2.0,Sur,15.99,15.000000,Moderado
5,6,Juan_V,Familiar,110.0,4.0,Este,22.99,27.500000,Intenso
6,7,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99,13.750000,Moderado
7,8,Pedro_S,Basico,8.0,1.0,Oeste,9.99,8.000000,Moderado
8,9,Carlos_Labs,Premium,42.0,3.0,Sur,15.99,14.000000,Moderado
9,10,Elena_M,Familiar,95.0,5.0,Norte,22.99,19.000000,Intenso
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99,15.000000,Moderado
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso
13,14,Andres_F,Basico,NaN,2.0,Sur,9.99,NaN,Moderado
14,15,Camila_R,Premium,50.0,NaN,Oeste,15.99,NaN,Moderado
15,16,Mateo_H,Familiar,120.0,6.0,Norte,22.99,20.000000,Intenso
16,17,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99,13.750000,Moderado
17,18,Diego_S,Basico,5.0,1.0,Este,9.99,5.000000,Moderado
18,19,Valentina_M,Premium,75.0,3.0,NaN,15.99,25.000000,Intenso
19,20,Javier_A,Familiar,NaN,4.0,Sur,22.99,NaN,Moderado
20,21,Andres_F,Basico,NaN,2.0,Sur,9.99,NaN,Moderado
21,22,Laura_Q,Basico,18.0,1.0,Norte,9.99,18.000000,Moderado
22,23,Gabriel_P,Premium,60.0,3.0,Oeste,NaN,20.000000,Moderado
23,24,Isabella_Z,Familiar,105.0,5.0,Este,22.99,21.000000,Intenso
24,25,Lucas_W,Basico,22.0,NaN,Sur,9.99,NaN,Moderado
25,26,Ana_Gomez,Premium,65.0,3.0,Norte,15.99,21.666667,Intenso
26,27,Nicolas_K,Premium,NaN,2.0,Norte,15.99,NaN,Moderado
27,28,Daniela_O,Basico,14.0,1.0,NaN,9.99,14.000000,Moderado
28,29,Tomas_L,Familiar,88.0,4.0,Este,22.99,22.000000,Intenso
29,30,Martina_X,Premium,40.0,3.0,Oeste,15.99,13.333333,Moderado
30,31,Javier_A,Familiar,NaN,4.0,Sur,22.99,NaN,Moderado
31,32,Samuel_V,Basico,9.0,1.0,Sur,9.99,9.000000,Moderado
32,33,Valeria_B,Premium,92.0,3.0,Norte,15.99,30.666667,Intenso
33,34,Benjamin_N,Familiar,130.0,5.0,Este,22.99,26.000000,Intenso
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso
35,36,Mia_P,Basico,31.0,2.0,Oeste,9.99,15.500000,Moderado
36,37,Joaquin_M,Premium,48.0,2.0,NaN,15.99,24.000000,Moderado
37,38,Elena_M,Familiar,95.0,5.0,Norte,22.99,19.000000,Intenso
38,39,Alejandro_C,Basico,11.0,1.0,Sur,9.99,11.000000,Moderado
39,40,Sofia_Corp,Premium,55.0,4.0,Oeste,15.99,13.750000,Moderado
40,41,Zoe_T,Premium,67.0,3.0,Norte,15.99,22.333333,Intenso
41,42,Matías_U,Familiar,NaN,4.0,Este,22.99,NaN,Moderado
42,43,Victoria_I,Basico,25.0,2.0,Oeste,9.99,12.500000,Moderado
43,44,Carlos_Perez,Basico,12.0,1.0,Sur,9.99,12.000000,Moderado
44,45,Sara_E,Premium,58.0,3.0,Sur,15.99,19.333333,Moderado
45,46,Daniel_Y,Familiar,115.0,5.0,Norte,22.99,23.000000,Intenso
46,47,Simon_D,Basico,4.0,1.0,Este,9.99,4.000000,Moderado
47,48,Catalina_L,Premium,82.0,3.0,Oeste,15.99,27.333333,Intenso
48,49,Tomas_L,Familiar,88.0,4.0,Este,22.99,22.000000,Intenso
49,50,Amanda_F,Basico,NaN,1.0,Sur,9.99,NaN,Moderado

## **🍿 Desafío 8: Transformación y estandarización de texto** ##

**Contexto:** Para evitar errores en las bases de datos de correos masivos, el equipo de sistemas requiere estandarizar el formato de los planes.

**Objetivo:** Modifica la columna existente Tipo_Suscripcion para que todos sus valores queden guardados completamente en letras minúsculas (por ejemplo, transformar 'Premium' en 'premium').

**Pista:** Pandas tiene un accesorio especial para trabajar con textos llamado .str. Para convertir a minúsculas se usa el método .lower(). La estructura para sobrescribir una columna es:df['Columna'] = df['Columna'].str.lower()

In [52]:
df_streaming['Tipo_Suscripcion'] = df_streaming['Tipo_Suscripcion'].str.lower()
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo
0,1,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso
1,2,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado
2,3,Mariana_Tech,familiar,85.0,5.0,Este,22.99,17.000000,Intenso
3,4,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado
4,5,Ana_Martínez,premium,30.0,2.0,Sur,15.99,15.000000,Moderado
5,6,Juan_V,familiar,110.0,4.0,Este,22.99,27.500000,Intenso
6,7,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado
7,8,Pedro_S,basico,8.0,1.0,Oeste,9.99,8.000000,Moderado
8,9,Carlos_Labs,premium,42.0,3.0,Sur,15.99,14.000000,Moderado
9,10,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99,15.000000,Moderado
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso
13,14,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado
14,15,Camila_R,premium,50.0,NaN,Oeste,15.99,NaN,Moderado
15,16,Mateo_H,familiar,120.0,6.0,Norte,22.99,20.000000,Intenso
16,17,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado
17,18,Diego_S,basico,5.0,1.0,Este,9.99,5.000000,Moderado
18,19,Valentina_M,premium,75.0,3.0,NaN,15.99,25.000000,Intenso
19,20,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado
20,21,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado
21,22,Laura_Q,basico,18.0,1.0,Norte,9.99,18.000000,Moderado
22,23,Gabriel_P,premium,60.0,3.0,Oeste,NaN,20.000000,Moderado
23,24,Isabella_Z,familiar,105.0,5.0,Este,22.99,21.000000,Intenso
24,25,Lucas_W,basico,22.0,NaN,Sur,9.99,NaN,Moderado
25,26,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso
26,27,Nicolas_K,premium,NaN,2.0,Norte,15.99,NaN,Moderado
27,28,Daniela_O,basico,14.0,1.0,NaN,9.99,14.000000,Moderado
28,29,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso
29,30,Martina_X,premium,40.0,3.0,Oeste,15.99,13.333333,Moderado
30,31,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado
31,32,Samuel_V,basico,9.0,1.0,Sur,9.99,9.000000,Moderado
32,33,Valeria_B,premium,92.0,3.0,Norte,15.99,30.666667,Intenso
33,34,Benjamin_N,familiar,130.0,5.0,Este,22.99,26.000000,Intenso
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso
35,36,Mia_P,basico,31.0,2.0,Oeste,9.99,15.500000,Moderado
36,37,Joaquin_M,premium,48.0,2.0,NaN,15.99,24.000000,Moderado
37,38,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso
38,39,Alejandro_C,basico,11.0,1.0,Sur,9.99,11.000000,Moderado
39,40,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado
40,41,Zoe_T,premium,67.0,3.0,Norte,15.99,22.333333,Intenso
41,42,Matías_U,familiar,NaN,4.0,Este,22.99,NaN,Moderado
42,43,Victoria_I,basico,25.0,2.0,Oeste,9.99,12.500000,Moderado
43,44,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado
44,45,Sara_E,premium,58.0,3.0,Sur,15.99,19.333333,Moderado
45,46,Daniel_Y,familiar,115.0,5.0,Norte,22.99,23.000000,Intenso
46,47,Simon_D,basico,4.0,1.0,Este,9.99,4.000000,Moderado
47,48,Catalina_L,premium,82.0,3.0,Oeste,15.99,27.333333,Intenso
48,49,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso
49,50,Amanda_F,basico,NaN,1.0,Sur,9.99,NaN,Moderado

## **🍿 Desafío 9: Multiplicación condicional (Cálculo de Comisiones/Impuestos)** ##

**Contexto:** El departamento de finanzas va a aplicar un impuesto digital del 10% (0.10) sobre el costo del plan mensual, pero únicamente a los usuarios de la región 'Norte'. A las demás regiones se les aplicará un 0% (0).

**Objetivo:** Crea una nueva columna llamada Impuesto_Digital que calcule el valor en dinero de ese impuesto (es decir, multiplicar Monto_Mensual_USD * 0.10 si es del Norte, o guardar 0 si es de otra región).

In [53]:
df_streaming['Impuesto_Digital'] = np.where(df_streaming['Region_Usuario']=='Norte', df_streaming['Monto_Mensual_USD']*0.10, 0)
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital
0,1,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599
1,2,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000
2,3,Mariana_Tech,familiar,85.0,5.0,Este,22.99,17.000000,Intenso,0.000
3,4,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999
4,5,Ana_Martínez,premium,30.0,2.0,Sur,15.99,15.000000,Moderado,0.000
5,6,Juan_V,familiar,110.0,4.0,Este,22.99,27.500000,Intenso,0.000
6,7,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000
7,8,Pedro_S,basico,8.0,1.0,Oeste,9.99,8.000000,Moderado,0.000
8,9,Carlos_Labs,premium,42.0,3.0,Sur,15.99,14.000000,Moderado,0.000
9,10,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99,15.000000,Moderado,0.000
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso,0.000
13,14,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000
14,15,Camila_R,premium,50.0,NaN,Oeste,15.99,NaN,Moderado,0.000
15,16,Mateo_H,familiar,120.0,6.0,Norte,22.99,20.000000,Intenso,2.299
16,17,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000
17,18,Diego_S,basico,5.0,1.0,Este,9.99,5.000000,Moderado,0.000
18,19,Valentina_M,premium,75.0,3.0,NaN,15.99,25.000000,Intenso,0.000
19,20,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000
20,21,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000
21,22,Laura_Q,basico,18.0,1.0,Norte,9.99,18.000000,Moderado,0.999
22,23,Gabriel_P,premium,60.0,3.0,Oeste,NaN,20.000000,Moderado,0.000
23,24,Isabella_Z,familiar,105.0,5.0,Este,22.99,21.000000,Intenso,0.000
24,25,Lucas_W,basico,22.0,NaN,Sur,9.99,NaN,Moderado,0.000
25,26,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599
26,27,Nicolas_K,premium,NaN,2.0,Norte,15.99,NaN,Moderado,1.599
27,28,Daniela_O,basico,14.0,1.0,NaN,9.99,14.000000,Moderado,0.000
28,29,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000
29,30,Martina_X,premium,40.0,3.0,Oeste,15.99,13.333333,Moderado,0.000
30,31,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000
31,32,Samuel_V,basico,9.0,1.0,Sur,9.99,9.000000,Moderado,0.000
32,33,Valeria_B,premium,92.0,3.0,Norte,15.99,30.666667,Intenso,1.599
33,34,Benjamin_N,familiar,130.0,5.0,Este,22.99,26.000000,Intenso,0.000
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso,0.000
35,36,Mia_P,basico,31.0,2.0,Oeste,9.99,15.500000,Moderado,0.000
36,37,Joaquin_M,premium,48.0,2.0,NaN,15.99,24.000000,Moderado,0.000
37,38,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299
38,39,Alejandro_C,basico,11.0,1.0,Sur,9.99,11.000000,Moderado,0.000
39,40,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000
40,41,Zoe_T,premium,67.0,3.0,Norte,15.99,22.333333,Intenso,1.599
41,42,Matías_U,familiar,NaN,4.0,Este,22.99,NaN,Moderado,0.000
42,43,Victoria_I,basico,25.0,2.0,Oeste,9.99,12.500000,Moderado,0.000
43,44,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000
44,45,Sara_E,premium,58.0,3.0,Sur,15.99,19.333333,Moderado,0.000
45,46,Daniel_Y,familiar,115.0,5.0,Norte,22.99,23.000000,Intenso,2.299
46,47,Simon_D,basico,4.0,1.0,Este,9.99,4.000000,Moderado,0.000
47,48,Catalina_L,premium,82.0,3.0,Oeste,15.99,27.333333,Intenso,0.000
48,49,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000
49,50,Amanda_F,basico,NaN,1.0,Sur,9.99,NaN,Moderado,0.000

## **🍿 Desafío 10: Múltiples condiciones avanzadas con np.select()** ##

**Contexto:** El equipo de soporte quiere clasificar las cuentas por su nivel de riesgo de saturación según los dispositivos que conectan simultáneamente.

**Objetivo:** Crea una nueva columna llamada Riesgo_Conexion bajo la siguiente lógica de tres niveles:    

**Si Dispositivos_Conectados es mayor o igual a 5, la etiqueta debe ser 'Alto'.    
Si Dispositivos_Conectados es igual a 3 o 4, la etiqueta debe ser 'Medio'.  
Si es menor o igual a 2, la etiqueta debe ser 'Bajo'.**

**Pista:** La lógica de np.select() funciona creando dos listas independientes: una para tus preguntas lógicas (condiciones) y otra para las respuestas (opciones). Ambas listas deben tener el mismo orden.

In [54]:
# 1. Creas la lista con todas tus condiciones lógicas
condiciones = [
    (df_streaming['Dispositivos_Conectados'] >= 5),  # Condición 1 (Alto)
    ((df_streaming['Dispositivos_Conectados'] == 3) | (df_streaming['Dispositivos_Conectados'] == 4)),  # Condición 2 (Medio)
    (df_streaming['Dispositivos_Conectados'] <= 2)   # Condición 3 (Bajo)
]

# 2. Creas la lista con los resultados correspondientes en el mismo orden
opciones = ['Alto', 'Medio', 'Bajo']

# 3. Aplicas np.select asignándolo a la nueva columna
df_streaming['Riesgo_Conexion'] = np.select(condiciones, opciones, default='Desconocido')

#Mostrar nueva columna
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.0,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.0,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.0,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.0,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.0,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
11,12,Roberto_M,premium,15.0,1.0,NaN,15.99,15.000000,Moderado,0.000,Bajo
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso,0.000,Medio
13,14,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.0,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.0,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
16,17,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
17,18,Diego_S,basico,5.0,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.0,3.0,NaN,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
21,22,Laura_Q,basico,18.0,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
22,23,Gabriel_P,premium,60.0,3.0,Oeste,NaN,20.000000,Moderado,0.000,Medio
23,24,Isabella_Z,familiar,105.0,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.0,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
25,26,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
26,27,Nicolas_K,premium,NaN,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.0,1.0,NaN,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.0,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
30,31,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.0,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.0,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.0,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso,0.000,Medio
35,36,Mia_P,basico,31.0,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.0,2.0,NaN,15.99,24.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
38,39,Alejandro_C,basico,11.0,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
39,40,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
40,41,Zoe_T,premium,67.0,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,NaN,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.0,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.0,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.0,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.0,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.0,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
49,50,Amanda_F,basico,NaN,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

## **🍿 Desafío 11: Detección de valores nulos globales con isna().sum()** ##

**Contexto:** Te entregan un nuevo lote de datos de streaming y necesitas hacer un diagnóstico rápido para saber exactamente cuántas celdas vacías tiene cada columna del DataFrame.

**Objetivo:** Escribe una línea de código que sume todos los valores nulos y te devuelva un conteo detallado por columna.

**Pista:**

In [55]:
df_streaming.isna().sum()

ID_Usuario                 0
Nombre_Usuario             0
Tipo_Suscripcion           0
Horas_Reproducidas         7
Dispositivos_Conectados    2
Region_Usuario             4
Monto_Mensual_USD          3
Horas_Por_Dispositivo      9
Perfil_Consumo             0
Impuesto_Digital           0
Riesgo_Conexion            0
dtype: int64

## **🍿 Desafío 12: Relleno estratégico con valores ficios (.fillna())** ##

**Contexto:** Descubres que algunos usuarios no tienen registrada su región (NaN). El equipo de sistemas te pide que, para no perder esos registros, les asignes la etiqueta por defecto 'No especificado'.

**Objetivo:** Rellena los valores nulos únicamente de la columna Region_Usuario con el texto 'No especificado' de forma permanente.

In [56]:
df_streaming['Region_Usuario'] = df_streaming['Region_Usuario'].fillna('No especificado')
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.0,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.0,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.0,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.0,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.0,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
11,12,Roberto_M,premium,15.0,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso,0.000,Medio
13,14,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.0,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.0,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
16,17,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
17,18,Diego_S,basico,5.0,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.0,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
21,22,Laura_Q,basico,18.0,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
22,23,Gabriel_P,premium,60.0,3.0,Oeste,NaN,20.000000,Moderado,0.000,Medio
23,24,Isabella_Z,familiar,105.0,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.0,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
25,26,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
26,27,Nicolas_K,premium,NaN,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.0,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.0,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
30,31,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.0,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.0,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.0,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.500000,Intenso,0.000,Medio
35,36,Mia_P,basico,31.0,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.0,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
38,39,Alejandro_C,basico,11.0,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
39,40,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
40,41,Zoe_T,premium,67.0,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,NaN,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.0,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.0,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.0,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.0,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.0,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
49,50,Amanda_F,basico,NaN,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

## **🍿 Desafío 13: Eliminación selectiva de filas (.dropna())** ##

**Contexto:** El reporte financiero mensual no puede tener imprecisiones. Si un usuario tiene la celda de Monto_Mensual_USD vacía (como el caso de Gabriel_P con ID 23), ese registro no es útil para la auditoría y la fila entera debe ser descartada.

**Objetivo:** Elimina por completo las filas del DataFrame donde la columna Monto_Mensual_USD contenga un valor nulo de forma permanente.  

**Pista:** Borra la fila completa si encuentra un NaN en esa columna específica.  

***df_streaming.dropna(subset=['Columna'], inplace=True)***

In [57]:
#Consulto los NaN en 'Monto_Mensual_USD'
df_streaming[df_streaming['Monto_Mensual_USD'].isna()]

#Guardo los registros que voy a eliminar en un nuevo dataframe
df_monto_nan = df_streaming[df_streaming['Monto_Mensual_USD'].isna()]

#Muestro los registros eliminados
df_monto_nan

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
12,13,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.5,Intenso,0.0,Medio
22,23,Gabriel_P,premium,60.0,3.0,Oeste,NaN,20.0,Moderado,0.0,Medio
34,35,Lucia_Tech,familiar,70.0,4.0,Este,NaN,17.5,Intenso,0.0,Medio

In [58]:
#Elimino los registros NaN en 'Monto_Mensual_USD'
df_streaming.dropna(subset=['Monto_Mensual_USD'], inplace=True)

#Muestro el dataframe sin los registros eliminados
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.0,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.0,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.0,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.0,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.0,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
10,11,Luis_G,basico,45.0,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
11,12,Roberto_M,premium,15.0,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.0,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.0,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
16,17,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
17,18,Diego_S,basico,5.0,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.0,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
21,22,Laura_Q,basico,18.0,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
23,24,Isabella_Z,familiar,105.0,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.0,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
25,26,Ana_Gomez,premium,65.0,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
26,27,Nicolas_K,premium,NaN,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.0,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.0,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
30,31,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.0,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.0,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.0,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
35,36,Mia_P,basico,31.0,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.0,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.0,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
38,39,Alejandro_C,basico,11.0,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
39,40,Sofia_Corp,premium,55.0,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
40,41,Zoe_T,premium,67.0,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,NaN,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.0,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.0,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.0,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.0,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.0,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.0,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.0,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
49,50,Amanda_F,basico,NaN,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

## **🍿 Desafío 14: Relleno inteligente con estadísticas (Media / Promedio)** ##

**Contexto:** Notaste que hay varios usuarios con las Horas_Reproducidas vacías (como Andres_F o Javier_A). El equipo de producto te dice que no quieren borrar a estos usuarios, pero tampoco quieren ponerles un 0 porque alteraría las métricas. Te piden que llenes esos vacíos con el promedio (media) de horas de toda la plataforma.

**Objetivo:** Rellena los valores nulos de la columna Horas_Reproducidas usando la media calculada de esa misma columna de forma permanente.

**Pista:** Sintaxis para modificar la columna de forma permanente. 

***df['columna_numerica'] = df['columna_numerica'].fillna(df['columna_numerica'].mean())***

In [59]:
#Consultar horas reproducidas vacías
df_streaming[df_streaming['Horas_Reproducidas'].isna()]

#Llevo esos registros a un nuevo dataframe
df_horas_na = df_streaming[df_streaming['Horas_Reproducidas'].isna()].copy()

#Muestro el dataframe
df_horas_na

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
13,14,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
19,20,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,NaN,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
26,27,Nicolas_K,premium,NaN,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
30,31,Javier_A,familiar,NaN,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
41,42,Matías_U,familiar,NaN,4.0,Este,22.99,NaN,Moderado,0.000,Medio
49,50,Amanda_F,basico,NaN,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

In [60]:
#Método 1:
#Calculo la media
media_horas_reproducidas = df_streaming['Horas_Reproducidas'].mean()
media_horas_reproducidas

#En el dataframe df_horas_na imputo la media 
df_horas_na['Horas_Reproducidas'] = df_horas_na['Horas_Reproducidas'].fillna(media_horas_reproducidas)

#Muestro el dataframe
df_horas_na

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
30,31,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

In [61]:
#Método 2:

#Calculo la media
media_horas_reproducidas = df_streaming['Horas_Reproducidas'].mean()
media_horas_reproducidas

#A los valores vacíos de la columba horas reproducidas les asigno la media que calculé en una variable
df_streaming['Horas_Reproducidas'] = df_streaming['Horas_Reproducidas'].fillna(media_horas_reproducidas)

#Muestro el dataframe
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
10,11,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
11,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
16,17,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
17,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
21,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
23,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
25,26,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
30,31,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
35,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
38,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
39,40,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
40,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

In [62]:
#Método 3:
#Hago todo en una línea, sin crear variable con la media
df_streaming['Horas_Reproducidas'] = df_streaming['Horas_Reproducidas'].fillna(df_streaming['Horas_Reproducidas'].mean())

#Muestro el dataframe
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
10,11,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
11,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
16,17,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
17,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
21,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
23,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
25,26,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
30,31,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
35,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
38,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
39,40,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
40,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

## **🍿 Desafío 15: Limpieza de espacios invisibles en texto (.str.strip())** ##

**Contexto:** Al importar datos desde archivos CSV o formularios web, es muy común que los usuarios o los sistemas inserten accidentalmente espacios en blanco invisibles al principio o al final de las palabras (por ejemplo, 'Norte ' o ' Norte'). Esto hace que Pandas los trate como categorías diferentes a 'Norte', dañando tus filtros y reportes.

**Objetivo:** Limpia la columna Region_Usuario eliminando cualquier espacio en blanco oculto al inicio o al final de los textos de forma permanente.

**Pista:** Pandas cuenta con un método vectorizado de texto diseñado específicamente para "recortar" estos espacios invisibles. Para guardar los cambios de forma definitiva, debes sobrescribir la columna usando la siguiente estructura:

***df['columna_texto'] = df['columna_texto'].str.strip()***

In [63]:
df_streaming['Region_Usuario'] = df_streaming['Region_Usuario'].str.strip()
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
10,11,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
11,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
16,17,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
17,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
20,21,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
21,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
23,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
25,26,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
30,31,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
35,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
38,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
39,40,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
40,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

## **🍿 Desafío 16: Detección visual de filas duplicadas (.duplicated())** ##

**Contexto:** Antes de borrar cualquier dato de la plataforma, necesitas presentar un informe a la gerencia que muestre cuáles son exactamente las filas que están repetidas en la base de datos, para demostrar que hay un problema en el sistema de registro.

**Objetivo:** Filtra el DataFrame para mostrar en pantalla únicamente aquellas filas que sean copias idénticas de un registro anterior.

**Pista:** Pandas cuenta con un método que revisa fila por fila y devuelve True si esa fila ya apareció antes en la tabla. Para aislar y ver esos registros duplicados dentro de tu DataFrame, se usa la siguiente estructura de filtrado:

***df_duplicados = df[df.duplicated()]***

In [64]:
#Ordeno el dataframe para comprobar que hay nombres duplicados
df_streaming.sort_values('Nombre_Usuario')

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
38,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
25,26,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
20,21,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
33,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
14,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
45,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
27,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
17,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
37,38,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
23,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
30,31,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
36,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
21,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
24,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
10,11,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
29,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
15,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
35,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
11,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
31,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
46,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
16,17,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
39,40,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
28,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
48,49,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
18,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
32,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
42,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
40,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio

In [65]:
#Este nuevo df no muestra duplicados porque el ID_Usuario es diferente aunque si hay registros que en los demas campos
#son iguales
df_duplicados = df_streaming[df_streaming.duplicated()]
df_duplicados

#"Busca duplicados basándote solo en el Nombre_Usuario"
df_duplicados = df_streaming[df_streaming.duplicated(subset=['Nombre_Usuario'])]
df_duplicados.sort_values('Nombre_Usuario')

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
25,26,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
20,21,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
43,44,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
37,38,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
30,31,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
10,11,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
16,17,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
39,40,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
48,49,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio

## **🍿 Desafío 17: Eliminación de filas duplicadas idénticas** ##

**Contexto:** Ahora que confirmamos que existen usuarios repetidos en la plataforma con diferentes IDs de registro (como Sofia_Corp o Andres_F), debes limpiar el DataFrame principal para conservar únicamente la primera aparición de cada cliente y eliminar los registros redundantes.

**Objetivo:** Elimina de forma permanente las filas duplicadas del DataFrame df_streaming tomando como criterio exclusivo la columna Nombre_Usuario.

**Pista:** Para borrar registros basados en una columna específica y aplicar el cambio de manera directa en la tabla original, se pasa el nombre de la columna dentro de una lista al argumento subset combinado con la persistencia:

***df.drop_duplicates(subset=['nombre_columna'], inplace=True)***

**Nota:** En Pandas, por defecto, casi todos los métodos de limpieza o transformación (como .drop_duplicates(), .dropna(), .fillna(), o .sort_values()) no modifican tus datos originales. Lo que hacen es crear una copia modificada en la memoria RAM y mostrártela en la pantalla.

In [66]:
df_streaming.drop_duplicates(subset=['Nombre_Usuario'], inplace=True)

df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
11,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
17,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
21,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
23,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
35,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
38,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
40,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

## **🍿 Desafío 18: Conservar la última aparición en lugar de la primera (keep='last')** ##

**Contexto:** En algunas auditorías de plataformas de streaming, el equipo de sistemas prefiere que, si un usuario se registró dos veces, se elimine el registro viejo y se conserve el registro más reciente (es decir, la última aparición en la tabla), ya que suele contener los datos de consumo actualizados.

**Objetivo:** Realiza una prueba de eliminación de duplicados basada en Nombre_Usuario de forma permanente, pero esta vez indícale a Pandas que conserve la última fila repetida en lugar de la primera.

**Pista:** Por defecto, Pandas usa el comportamiento keep='first'. Si quieres cambiarlo para que guarde el último registro y borre los anteriores, debes agregar el argumento keep='last'. La estructura queda así:

***df.drop_duplicates(subset=['nombre_columna'], keep='last', inplace=True)***

In [67]:
df_streaming.drop_duplicates(subset=['Nombre_Usuario'],keep='last', inplace=True)

## **🍿 Desafío 19:  El equivalente al BUSCARV / JOIN Interno (.merge())** ##

**Contexto:** El departamento de finanzas quiere verificar si lo que paga cada usuario en tu tabla df_streaming coincide con la tabla oficial de precios df_tarifas. Para lograrlo, necesitas cruzar ambas tablas usando como puente la columna común que comparten.

**Objetivo:** Une el DataFrame df_streaming con df_tarifas realizando un cruce interno basado en la columna Tipo_Suscripcion.

**Pista:** Para fusionar dos tablas horizontalmente usando una columna puente, Pandas utiliza el método .merge(). La estructura básica para guardar el resultado en un nuevo DataFrame es:

***df_resultado = df_izquierda.merge(df_derecha, on='columna_puente', how='inner')***

In [68]:
#Cargar df tarifas (para ejercicios 19 en adelante)
df_tarifas = pd.read_csv('/Users/nando/Ejercicios-Practica-Python/Ciencia de datos/Laboratorio Streaming/tarifas_streaming.csv')
df_tarifas

  Tipo_Suscripcion  Precio_Oficial Soporte_4K
0          premium           15.99         Si
1           basico            9.99         No
2         familiar           22.99         Si

In [69]:
df_streaming

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto
11,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo
13,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo
14,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido
15,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto
17,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo
18,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio
19,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio
21,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo
23,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto
24,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido
26,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo
27,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo
28,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio
29,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio
31,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo
32,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio
33,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto
35,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo
36,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo
38,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo
40,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio
41,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio
42,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo
44,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio
45,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto
46,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo
47,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio
49,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo

In [70]:
#Unir los df
df_unido = df_streaming.merge(df_tarifas, on=['Tipo_Suscripcion'], how='inner')
df_unido

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion,Precio_Oficial,Soporte_4K
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio,15.99,Si
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo,9.99,No
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto,22.99,Si
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo,9.99,No
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo,15.99,Si
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio,22.99,Si
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio,15.99,Si
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo,9.99,No
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio,15.99,Si
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto,22.99,Si
10,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo,15.99,Si
11,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo,9.99,No
12,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido,15.99,Si
13,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto,22.99,Si
14,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo,9.99,No
15,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio,15.99,Si
16,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio,22.99,Si
17,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo,9.99,No
18,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto,22.99,Si
19,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido,9.99,No
20,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo,15.99,Si
21,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo,9.99,No
22,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio,22.99,Si
23,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio,15.99,Si
24,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo,9.99,No
25,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio,15.99,Si
26,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto,22.99,Si
27,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo,9.99,No
28,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo,15.99,Si
29,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo,9.99,No
30,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio,15.99,Si
31,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio,22.99,Si
32,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo,9.99,No
33,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio,15.99,Si
34,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto,22.99,Si
35,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo,9.99,No
36,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio,15.99,Si
37,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo,9.99,No

## **🍿 Desafío 20:  Manejo de columnas puente con nombres diferentes** ##

**Contexto:** A veces las bases de datos no están estandarizadas. Imagina que te dan una tabla de promociones donde la columna del plan no se llama Tipo_Suscripcion, sino que la nombraron simplemente Plan. Necesitas cruzar tus datos aunque los títulos de las columnas puente no se llamen igual.

**Objetivo:** Fusiona df_streaming con una tabla externa indicándole explícitamente que la columna puente en la izquierda se llama Tipo_Suscripcion y en la derecha se llama Plan.

**Pista:** Si las columnas puente tienen nombres distintos, el argumento on no funcionará. Debes usar left_on y right_on para guiar a Pandas en el cruce:

***df_resultado = df_izq.merge(df_der, left_on='columna_izq', right_on='columna_der', how='inner')***

In [71]:
#Copio el df tarifas para cambiar el nombre de la columna para este ejercicio

df_tarifas2 = df_tarifas.copy()
df_tarifas2

  Tipo_Suscripcion  Precio_Oficial Soporte_4K
0          premium           15.99         Si
1           basico            9.99         No
2         familiar           22.99         Si

In [72]:
#Cambio el nombre de la columba Tipo_Suscripcion por plan

#Listo las columnas
df_tarifas2.columns

#Renombro la columna Tipo_Suscripcion
df_tarifas2 = df_tarifas2.rename(columns={'Tipo_Suscripcion':'Plan'})

#Muestro el nuevo dataframe
df_tarifas2

       Plan  Precio_Oficial Soporte_4K
0   premium           15.99         Si
1    basico            9.99         No
2  familiar           22.99         Si

In [73]:
df_resultado = df_streaming.merge(df_tarifas2, left_on='Tipo_Suscripcion', right_on='Plan', how='inner')

#Muestro el nuevo dataframe
df_resultado

,ID_Usuario,Nombre_Usuario,Tipo_Suscripcion,Horas_Reproducidas,Dispositivos_Conectados,Region_Usuario,Monto_Mensual_USD,Horas_Por_Dispositivo,Perfil_Consumo,Impuesto_Digital,Riesgo_Conexion,Plan,Precio_Oficial,Soporte_4K
0,1,Ana_Gomez,premium,65.00,3.0,Norte,15.99,21.666667,Intenso,1.599,Medio,premium,15.99,Si
1,2,Carlos_Perez,basico,12.00,1.0,Sur,9.99,12.000000,Moderado,0.000,Bajo,basico,9.99,No
2,3,Mariana_Tech,familiar,85.00,5.0,Este,22.99,17.000000,Intenso,0.000,Alto,familiar,22.99,Si
3,4,Luis_G,basico,45.00,2.0,Norte,9.99,22.500000,Moderado,0.999,Bajo,basico,9.99,No
4,5,Ana_Martínez,premium,30.00,2.0,Sur,15.99,15.000000,Moderado,0.000,Bajo,premium,15.99,Si
5,6,Juan_V,familiar,110.00,4.0,Este,22.99,27.500000,Intenso,0.000,Medio,familiar,22.99,Si
6,7,Sofia_Corp,premium,55.00,4.0,Oeste,15.99,13.750000,Moderado,0.000,Medio,premium,15.99,Si
7,8,Pedro_S,basico,8.00,1.0,Oeste,9.99,8.000000,Moderado,0.000,Bajo,basico,9.99,No
8,9,Carlos_Labs,premium,42.00,3.0,Sur,15.99,14.000000,Moderado,0.000,Medio,premium,15.99,Si
9,10,Elena_M,familiar,95.00,5.0,Norte,22.99,19.000000,Intenso,2.299,Alto,familiar,22.99,Si
10,12,Roberto_M,premium,15.00,1.0,No especificado,15.99,15.000000,Moderado,0.000,Bajo,premium,15.99,Si
11,14,Andres_F,basico,54.65,2.0,Sur,9.99,NaN,Moderado,0.000,Bajo,basico,9.99,No
12,15,Camila_R,premium,50.00,NaN,Oeste,15.99,NaN,Moderado,0.000,Desconocido,premium,15.99,Si
13,16,Mateo_H,familiar,120.00,6.0,Norte,22.99,20.000000,Intenso,2.299,Alto,familiar,22.99,Si
14,18,Diego_S,basico,5.00,1.0,Este,9.99,5.000000,Moderado,0.000,Bajo,basico,9.99,No
15,19,Valentina_M,premium,75.00,3.0,No especificado,15.99,25.000000,Intenso,0.000,Medio,premium,15.99,Si
16,20,Javier_A,familiar,54.65,4.0,Sur,22.99,NaN,Moderado,0.000,Medio,familiar,22.99,Si
17,22,Laura_Q,basico,18.00,1.0,Norte,9.99,18.000000,Moderado,0.999,Bajo,basico,9.99,No
18,24,Isabella_Z,familiar,105.00,5.0,Este,22.99,21.000000,Intenso,0.000,Alto,familiar,22.99,Si
19,25,Lucas_W,basico,22.00,NaN,Sur,9.99,NaN,Moderado,0.000,Desconocido,basico,9.99,No
20,27,Nicolas_K,premium,54.65,2.0,Norte,15.99,NaN,Moderado,1.599,Bajo,premium,15.99,Si
21,28,Daniela_O,basico,14.00,1.0,No especificado,9.99,14.000000,Moderado,0.000,Bajo,basico,9.99,No
22,29,Tomas_L,familiar,88.00,4.0,Este,22.99,22.000000,Intenso,0.000,Medio,familiar,22.99,Si
23,30,Martina_X,premium,40.00,3.0,Oeste,15.99,13.333333,Moderado,0.000,Medio,premium,15.99,Si
24,32,Samuel_V,basico,9.00,1.0,Sur,9.99,9.000000,Moderado,0.000,Bajo,basico,9.99,No
25,33,Valeria_B,premium,92.00,3.0,Norte,15.99,30.666667,Intenso,1.599,Medio,premium,15.99,Si
26,34,Benjamin_N,familiar,130.00,5.0,Este,22.99,26.000000,Intenso,0.000,Alto,familiar,22.99,Si
27,36,Mia_P,basico,31.00,2.0,Oeste,9.99,15.500000,Moderado,0.000,Bajo,basico,9.99,No
28,37,Joaquin_M,premium,48.00,2.0,No especificado,15.99,24.000000,Moderado,0.000,Bajo,premium,15.99,Si
29,39,Alejandro_C,basico,11.00,1.0,Sur,9.99,11.000000,Moderado,0.000,Bajo,basico,9.99,No
30,41,Zoe_T,premium,67.00,3.0,Norte,15.99,22.333333,Intenso,1.599,Medio,premium,15.99,Si
31,42,Matías_U,familiar,54.65,4.0,Este,22.99,NaN,Moderado,0.000,Medio,familiar,22.99,Si
32,43,Victoria_I,basico,25.00,2.0,Oeste,9.99,12.500000,Moderado,0.000,Bajo,basico,9.99,No
33,45,Sara_E,premium,58.00,3.0,Sur,15.99,19.333333,Moderado,0.000,Medio,premium,15.99,Si
34,46,Daniel_Y,familiar,115.00,5.0,Norte,22.99,23.000000,Intenso,2.299,Alto,familiar,22.99,Si
35,47,Simon_D,basico,4.00,1.0,Este,9.99,4.000000,Moderado,0.000,Bajo,basico,9.99,No
36,48,Catalina_L,premium,82.00,3.0,Oeste,15.99,27.333333,Intenso,0.000,Medio,premium,15.99,Si
37,50,Amanda_F,basico,54.65,1.0,Sur,9.99,NaN,Moderado,0.000,Bajo,basico,9.99,No

## **🍿 Desafío 21:  Añadir/Unir registros nuevos al final de un dataframe (.concat())** ##

**Contexto:** Llegó el fin de mes y el equipo de sistemas te entrega un lote extra de usuarios nuevos que se registraron hoy en una tabla llamada df_nuevos. Necesitas "pegar" estas filas exactamente debajo de tu DataFrame actual para consolidar la base de datos.

**Objetivo:** Une verticalmente tu DataFrame actual df_streaming con la tabla df_nuevos.

**Pista:** Para apilar o pegar tablas una debajo de la otra (añadir filas), Pandas utiliza la función pd.concat(). Es muy importante pasar las tablas dentro de una lista y usar el argumento ignore_index=True para que los números de las filas se reordenen limpiamente de arriba a abajo:

***df_consolidado = pd.concat([df_1, df_2], ignore_index=True)***

In [ ]:
#Debemos tener un df_delta para que funcione esata solución
df_consolidado = pd.concat([df_streaming, df_delta], ignore_index=True)

## **🍿 Desafío 22:  Preservar la tabla principal con un Cruce Izquierdo (Left Join)** ##

**Contexto:** Te entregan una tabla de cupones de descuento aplicada a algunos usuarios. Quieres cruzar tu tabla df_streaming con esta nueva tabla, pero necesitas asegurarte de que ningún usuario de tu plataforma se borre del mapa, incluso si no aplicó ningún cupón (en cuyo caso la columna del cupón debería aparecer vacía o NaN).

**Objetivo:** Fusiona df_streaming con una tabla externa df_cupones usando como puente ID_Usuario, garantizando que todos los registros de la tabla izquierda se conserven intactos.

**Pista:** El cruce por defecto de Pandas (inner) borra las filas que no coinciden en ambas tablas. Si deseas obligar a Pandas a conservar el 100% de las filas de tu tabla inicial (la de la izquierda), debes cambiar el argumento how a 'left':

***df_resultado = df_izquierda.merge(df_derecha, on='columna_puente', how='left')***

In [ ]:
#Left join
df_resultado2 = df_streaming.merge(df_cupones, on='ID_Usuario', how='left')

## **🍿 Desafío 23:  Conservar absolutamente todo con un Cruce Completo (Outer Join)** ##

**Contexto:** El departamento de auditoría te da dos listas de registros de diferentes servidores y te pide cruzarlas por ID_Usuario. Como no quieren dejar cabos sueltos, te exigen que la tabla final contenga todos los usuarios de ambas listas, sin importar si coinciden o si solo aparecen en una de las dos tablas.

**Objetivo:** Fusiona df_streaming con otra tabla df_servidor2 realizando un cruce completo que conserve la unión total de los datos.

**Pista:**  Para traer la combinación total de ambas tablas y rellenar con NaN los lugares donde no hubo coincidencia (conservando filas tanto de la izquierda como de la derecha), se modifica el tipo de cruce a 'outer':

***df_resultado = df_izquierda.merge(df_derecha, on='columna_puente', how='outer')***

In [ ]:
#Outer join
df_resultado2 = df_streaming.merge(df_cupones, on='ID_Usuario', how='outer')